import { LanguageCode } from "@/JotoKit/ts/common";
import { Translation } from "@/JotoKit/ts/translations";

export const TRANSLATIONS_DE: Translation = {
    lang_value: LanguageCode.German,
    lang_names: {
        "en-US": "Englisch",
        "de-DE": "Deutsch",
        "es-ES": "Spanisch",
        "fr-FR": "Französisch",
        "nl-NL": "Niederländisch",
        "sv-SE": "Schwedisch",
        ru: "Russisch",
        hu: "Ungarisch",
        "sl-SI": "Slovenisch",
        "ja-JP": "Japanisch",
    },
    searchbar: {
        placeholder: "Suchen...",
        rad_picker: {
            select_kanji: "Kanji wählen",
            search_placeholder: "Kanji eingeben...",
            select_kanji_placeholder: "Wähle ein Radikal zum starten der Kanji-Suche",
        },
        image_overlay: {
            select: "Wähle ein Bild",
            picture: "Mache ein neues Bild",
            error: "Konnte keinen Text finden!",
        },
        voice_overlay: {
            start: "Tippe zum starten",
            stop: "Tippe zum beenden",
            listening: "Wartet auf Sprachende",
            not_listening: "Wartet auf Startsignal",
            perm_denied: "Mikrofon-Berechtigung konnte nicht erlangt werden. Bitte schalte sie manuell frei, wenn nötig!",
        },
        categories: {
            words: "Wörter",
            kanji: "Kanji",
            sentences: "Sätze",
            names: "Namen",
        },
    },
    navbar: {
        title: {
            settings: "Einstellungen",
            links: "Links",
        },
        action_button: {
            language: "Sprache",
            search: "Suche",
            display: "Darstellung",
            qol: "Bedienung",
            privacy: "Privatsphäre",
            github: "Github",
            donation: "Spenden",
            discord: "Discord",
            instagram: "Instagram",
            about: "Über uns",
        },
        nav_button: {
            home: "Hauptmenü",
            back: "Zurück",
            exit: "App beenden",
        },
    },
    settings: {
        language: {
            title_language: "Spracheinstellungen",
            title_langSelect: "Sprachauswahl",
            select_search: "Sprache für Suchanfragen",
            select_page: "Sprache der Anwendung",
            title_ordering: "Einordnung",
            checkbox_alwaysEnglish: "Zeige immer englische Ergebnisse",
            checkbox_englishOnTop: "Zeige englische Ergebnisse als Erstes",
        },
        search: {
            title_words: "Wörter",
            checkbox_showExampleSentences: "Zeige Beispielsätze",
            title_sentences: "Sätze",
            checkbox_showFuri: "Zeige Furigana",
            checkbox_hideTranslation: "Verstecke Übersetzung",
            title_kanji: "Kanji-Suche",
            anim_speed: "Animationsgeschwindigkeit",
            show_other_langs: "zeige weitere Sprachen",
            show_kanji: "Zeige Kanji beim Laden",
            show_numbers: "Zeige Reihenfolge mit Nummern an",
        },
        display: {
            title_theme: "Farbschema",
            option_auto: "Automatisch",
            option_dark: "Dunkel",
            option_light: "Hell",
            title_itemsPerPage: "Seiteneinträge",
            words_per_page: "Wörter pro Seite",
            kanji_per_page: "Kanji pro Seite",
            names_per_page: "Namen pro Seite",
            sentences_per_page: "Sätze pro Seite",
        },
        qol: {
            title_search: "Suchleiste",
            checkbox_search_anim: "Zeige Inputbeispiele",
            checkbox_index_keyboard: "Beende die App beim schließen des Index-Keyboards",
            checkbox_focusAfterSearch: "Fokussiere Suchleiste nach einer Suche",
            checkbox_focusInputAfterSearch: "Markiere Input nach einer Suche",
            title_other: "Sonstiges",
            checkbox_use_japanese_fonts: "Verwende ausgewählte japanische Schriftarten",
            checkbox_enable_furi_copy: "Aktiviere Furigana-Copy",
        },
        privacy: {
            title_privacy: "Privatsphäre",
            allow_cookie: "Erlaube das Sammeln von Nutzerdaten",
            explanation:
                "Um Jotoba zu verbessern, sammeln wir vollständig anonymisierte Daten zur Webseitennutzung. Du kannst jedoch jederzeit aus der Sammlung aussteigen.",
        },
    },
    pages: {
        loader_messages: {
            0: "Zähle Wörter",
            1: "Zeichne Kanji",
            2: "Zähle bis unendlich",
            3: "Plane neue Features",
            4: "Bereite Popcorn zu",
            5: "Zähle einfach bis 10",
            6: "Suche das Wifi-Kabel",
            7: "Beweise P=NP",
            8: "Füge zufällige Rechtschreipfehler hinzu",
            9: "Stecke das W-LAN Kabel ein",
            10: "Mit Premium geht's schneller",
            11: "Behalte alle Einsen und entferne alle Nullen",
            12: "Bitte holt mich hir raus",
            13: "Erfinde weitere Lade-Nachrichten",
            14: "Übersetze 「よろしく」",
        },
        index: {
            search: "Suchen",
            radicals: "Radikale",
        },
        words: {
            common: "Häufiges Wort",
            jlpt: "JLPT N",
            audio: {
                tofugu: "Tofugu",
                kanjialive: "Kanji alive",
            },
            number: "{{query}} is {{number}}",
            inflection: "{{query}} könnte eine Flexion von {{word}} sein. Mögliche Form:",
            inflections: "{{query}} könnte eine Flexion von {{word}} sein. Mögliche Formen:",
            sentence_show: "Zeige langen Beispielsatz",
            sentence_hide: "Verstecke Beispielsatz",
            garaigo: "Wasei, {{language}} -> {{word}}",
            pitches: "Tonhöhenakzente",
            other_forms: "Andere Formen",
            three_dot: {
                show_collocations: "Zeige Kollokationen",
                show_conjugations: "Zeige Konjugationen",
                suffix_transitivity: "Wort",
                sentence_search: "Satz-Suche",
                download_audio_tofugu: "Tofugu Audio",
                download_audio_kanjialive: "Kanjialive Audio",
                direct_reference: "Detailansicht",
            },
            xref: "See also <word>{{word}}</word>",
            pos: {
                Noun: {
                    Normal: "Nomen",
                    Adverbial: "Adverbialnomen",
                    Prefix: "Präfix (Nomen)",
                    Suffix: "Suffix (Nomen)",
                    Temporal: "Zeitliches Substantiv",
                },
                Adjective: {
                    PreNounVerb: "Substantiv oder Verb, das ein Substantiv beschreibt",
                    Keiyoushi: "Ich Adjektiv",
                    KeiyoushiYoiIi: "Ich Adjectiv (Als いい konjugiert)",
                    Ku: "Ku-Adjektiv",
                    Na: "Na-Adjektiv",
                    Nari: "Formale Form vom Na-Adjektiv",
                    No: "No-Adjektiv",
                    PreNoun: "Vornomen Adjektiv",
                    Shiku: "Shiku-Adjektiv",
                    Taru: "Taru-Adjektiv",
                },
                Verb: {
                    Unspecified: "Unspezifiziertes Verb",
                    Intransitive: "Intransitives Verb",
                    Transitive: "Transitives Verb",
                    Ichidan: "Ichidan-Verb",
                    IchidanZuru: 'Ichidan "zuru"-Verb',
                    IchidanKureru: 'Ichidan "kureru"-Verb',
                    Kuru: "Kuru-Verb",
                    Nidan: {
                        class: {
                            Upper: "Oberes Nidan-Verb",
                            Lower: "Unteres Nidan-Verb",
                        },
                    },
                    Yodan: {
                        Bu: "Yodan Bu-Verb",
                        Dzu: "Yodan Dzu-Verb",
                        Gu: "Yodan Gu-Verb",
                        Hu: "Yodan Hu-Verb",
                        Ku: "Yodan Ku-Verb",
                        Mu: "Yodan Mu-Verb",
                        Nu: "Yodan Nu-Verb",
                        Ru: "Yodan Ru-Verb",
                        Su: "Yodan Su-Verb",
                        Tsu: "Yodan Tsu-Verb",
                        U: "Yodan U-Verb",
                        Yu: "Yodan Yu-Verb",
                        Zu: "Yodan Zu-Verb",
                    },
                    Godan: {
                        Bu: "Godan Bu-Verb",
                        Gu: "Godan Gu-Verb",
                        Ku: "Godan Ku-Verb",
                        Mu: "Godan Mu-Verb",
                        Nu: "Godan Nu-Verb",
                        Ru: "Godan Ru-Verb",
                        Su: "Godan Su-Verb",
                        Tsu: "Godan Tsu-Verb",
                        U: "Godan U-Verb",
                        Aru: "Godan Aru-Verb",
                        USpecial: "Godan U-Verb (Speziell)",
                        Uru: "Godan U-Verb",
                        RuIrreg: "Godan Ru-Verb (ungregelmäßig)",
                        IkuYuku: "Godan Iku-Verb",
                    },
                    Irregular: {
                        Nu: "Unregelmäßiges Verb, das auf nu endet",
                        Ru: "Unregelmäßiges Verb, das auf ru endet",
                        Su: "Unregelmäßiges Verb, das auf su endet",
                        NounOrAuxSuru: 'Substantiv mit "suru"',
                        Suru: "Suru-Verb",
                        SuruSpecial: "Speziales Suru",
                    },
                },
                Sfx: "SoundFx",
                Expr: "Ausdruck",
                Counter: "Zähler",
                Suffix: "Suffix",
                Prefix: "Präfix",
                Particle: "Partikel",
                Interjection: "Zwischenruf",
                Pronoun: "Pronomen",
                Numeric: "Numerisch",
                Adverb: "Adverb",
                AdverbTo: "To-Adverb",
                Auxilary: "Hilfsmittel",
                AuxilaryAdj: "Hilfsadjektiv",
                AuxilaryVerb: "Hilfsverb",
                Conjunction: "Konjugation",
                Unclassified: "Nicht klassifiziert",
            },
            word_class: {
                "Pre-noun": "Vornomen",
                Noun: "Nomen",
                Pronoun: "Pronomen",
                Adjective: "Adjektiv",
                Verb: "Verb",
                Adverb: "Adverb",
                Particle: "Partikel",
                Interjection: "Zwischenruf",
                Symbol: "Symbol",
                Conjugation: "Konjugation",
                Conjunction: "Verbindung",
                Suffix: "Suffix",
                Prefix: "Präfix",
                Space: "Leerzeichen",
            },
            field: {
                term: "Begriff",
                Agriculture: "Landwirtschaft",
                Anatomy: "Anatomie",
                Archeology: "Archäologie",
                Architecture: "Architektur",
                ArtAesthetics: "Kunstästhetik",
                Astronomy: "Astronomie",
                AudioVisual: "Audiovisuell",
                Aviation: "Luftfahrt",
                Baseball: "Baseball",
                Biochemistry: "Biochemie",
                Biology: "Biologie",
                Botany: "Botanik",
                Buddhism: "Buddhismus",
                Business: "Business",
                Chemistry: "Chemie",
                Christianity: "Christentum",
                Computing: "Computer",
                Clothing: "Kleidung",
                Crystallography: "Kristallographie",
                Ecology: "Ökologie",
                Economics: "Wirtschaft",
                Electricity: "Elektrizität",
                Electronics: "Elektronik",
                Embryology: "Embryologie",
                Engineering: "Ingenieurwesen",
                Entomology: "Entomologie",
                Finance: "Finanzen",
                Fishing: "Fischerei",
                FoodCooking: "Koch",
                Gardening: "Gärtnerei",
                Genetics: "Genetik",
                Geography: "Geografie",
                Geology: "Geologie",
                Geometry: "Geometrie",
                GoGame: "Go (game)",
                Golf: "Golf",
                Grammar: "Grammatik",
                GreekMythology: "Griechische Mythologie",
                Hanafuda: "Hanafuda",
                Horseracing: "Pferderennen",
                Law: "Recht",
                Linguistics: "Linguistik",
                Logic: "Logik",
                MartialArts: "Martial Arts",
                Mahjong: "Mahjong",
                Mathematics: "Mathemaik",
                MechanicalEngineering: "Maschinenbau",
                Medicine: "Medizin",
                ClimateWeather: "Klima / Wetter",
                Military: "Militär",
                Music: "Musik",
                Ornithology: "Vogelkunde",
                Paleontology: "Paläontologie",
                Pathology: "Pathologie",
                Pharmacy: "Pharmazie",
                Philosophy: "Philosophie",
                Photography: "Fotografie",
                Physics: "Physik",
                Physiology: "Physiologie",
                Printing: "Druckerei",
                Psychitatry: "Psychatrie",
                Shinto: "Shinto",
                Railway: "Eisenbahn",
                Shogi: "Shogi",
                Sports: "Sports",
                Statistics: "Statistik",
                Sumo: "Sumo",
                Telecommunications: "Telekommunikation",
                Trademark: "Trademark",
                Videogame: "Videospiel",
                Zoology: "Zoologie",
                Cards: "Karten",
                Dentistry: "Zahnmedizin",
                Kabuki: "Kabuki",
                Politics: "Politik",
                Psychology: "Psychologie",
            },
            misc: {
                Abbreviation: "Abkürzung",
                Archaism: "Archaismus",
                Character: "Charakter",
                ChildrensLanguage: "Kindersprache",
                Colloquialism: "Umgangssprache",
                CompanyName: "Firmenname",
                Creature: "Kreatur",
                DatedTerm: "Datierter Begriff",
                Deity: "Gottheit",
                Derogatory: "Abwertend",
                Document: "Dokument",
                Event: "Event",
                FamiliarLanguage: "Vertraute Sprache",
                FemaleTermOrLanguage: "Weblicher Begriff/Sprache",
                Fiction: "Fiktion",
                GivenName: "Vorname",
                Group: "Gruppe",
                HistoricalTerm: "Historischer Begriff",
                HonorificLanguage: "Höfliche Sprache",
                HumbleLanguage: "Bescheidene Sprache",
                IdiomaticExpression: "Idiomatischer Ausdruck",
                JocularHumorousTerm: "Scherzhafter humoristischer Begriff",
                Legend: "Legende",
                LiteraryOrFormalTerm: "Literarischer/formeller Begriff",
                MangaSlang: "Manga-Slang",
                MaleTermOrLanguage: "Männlicher Begriff/Sprache",
                Mythology: "Mythologie",
                InternetSlang: "Internet-Slang",
                Object: "Objekt",
                ObsoleteTerm: "Veralteter Begriff",
                ObscureTerm: "Unbekannter Begriff",
                OnomatopoeicOrMimeticWord: "Onomatopoetisches oder mimetisches Wort",
                OrganizationName: "Organisationsname",
                Other: "Andere",
                Personname: "Personenname",
                PlaceName: "Ortsname",
                PoeticalTerm: "Poetischer Begriff",
                PoliteLanguage: "Höfliche Sprache",
                ProductName: "Produktname",
                Proverb: "Sprichwort",
                Quotation: "Zitat",
                Rare: "Selten",
                Religion: "Religion",
                Sensitive: "Sensibel",
                Service: "Service",
                Slang: "Slang",
                RailwayStation: "Bahnhof",
                FamilyOrSurname: "Familien- oder Nachname",
                UsuallyWrittenInKana: "Üblicherweise in Kana geschrieben",
                UnclassifiedName: "Nicht klassifizierter Name",
                VulgarExpressionOrWord: "Vulgärer Ausdruck/Wort",
                ArtWork: "Kunstwerk",
                RudeOrXRatedTerm: "Nicht Jugendfreier Begriff",
                Yojijukugo: "Yojijukugo",
                Euphemistic: "Euphemistisch",
            },
        },
        kanji: {
            strokes: "{{stroke_count}} Striche",
            jlpt: "JLPT N{{jlpt}}",
            grade: "Beigebracht in der {{grade}}. Klasse",
            radical: "Radikal:",
            parts: "Teile:",
            kun: "Kun:",
            on: "On:",
            title_kun: "Kunyomi",
            title_on: "Onyomi",
            tooltip_stroke: "Anzahl der Striche",
            tooltip_grade: "Beigebracht in dieser Klasse",
            tooltip_jlpt: "JLPT-Level",
            tooltip_frequency: "Rang der Häufigkeit in Zeitschriften aus 2500",
            similar_kanji: "Similar:",
            reading_chinese: "Chinesisch:",
            reading_korean: "Koreanisch:",
            reading_vietnamese: "Vietnamesisch:",
            anim_reset: "Zurücksetzen",
        },
        names: {
            full_name: "Name",
            sex: "Geschlecht",
            origin: "Herkunft",
        },
        sentences: {
            source_kevin: "Kevin Goes to Japan",
            source_tatoeba: "Tatoeba",
            sentence_show: "[Zeigen]",
            sentence_hide: "[Verstecken]",
            three_dot: {
                sentence_search: "Satz-Suche",
                tatoeba_search: "Tatoeba-Suche",
                direct_reference: "Detailansicht",
            },
        },
        details: {
            common: {
                share: "Teilen",
            },
            tabs: {
                word: "Wort",
                words: "Wörter",
                kanji: "Kanji",
                sentence: "Satz",
                sentences: "Sätze",
                collocations: "Kollokationen",
                conjugations: "Konjugationen",
                more: "Mehr",
            },
            words: {
                conjugations: {
                    affirmative: "Positiv",
                    negative: "Negativ",
                    present: "Gegenwart",
                    present_polite: "Gegenwart (nett)",
                    past: "Vergangenheit",
                    past_polite: "Vergangenheit (nett)",
                    te_form: "Te-Form",
                    potential: "Potenzial",
                    passive: "Passiv",
                    causative: "Kausativ",
                    causative_passive: "Kausativ (Passiv)",
                    imperative: "Imperativ",
                },
                audio: {
                    tofugu: "Tofugu",
                    kanjialive: "Kanji alive",
                },
                switch: "Wechsel zu {{pair}}",
                Transitive: "Transitiv",
                Intransitive: "Intransitiv",
                jlpt: "JLPT-Level",
                frequency: "Häufigkeit",
            },
        },
        bookmarks: {
            undo: "Rückgängig",
            no_content:
                "<b>Du hast noch keine Vermerke.</b><br/><br/>Suche nach einem Wort, klicke es an und du kannst das Wort über das Icon in der oberen, linken Ecke hinzufügen!",
        },
        about: {
            title_about: "Über uns",
            content_about:
                "Jotoba ist ein mehrsprachiges Japanisch-Wörterbuch, mit dem es besonders einfach ist Übersetzungen zu Wörtern, Namen und Kanji zu finden und Beispielsätze zu entdecken. <br/><br/>" +
                "Besuche unsere <trello>Trello-Seite</trello>, wenn du an zukünftigen Features und unserer aktuellen Arbeit interessiert bist!",
            title_jotoKun: "Joto-kun",
            content_jotoKun:
                "Joto-kun wurde von einer guten Freundin erstellt, welche eine wahrere Zauberin ist, wenn es ums Designen geht!",
            title_wkn: "Wörter & Kanji & Namen",
            content_wkn:
                "Alle Daten über Wörter, Kanji und Namen auf dieser Webseite stammen von der <edrdg>EDRDG</edrdg> und stehen unter der <ccsa>CC BY-SA 3.0</ccsa> Lizenz.<br/><br/>" +
                "Des Weiteren verwenden wir die RADKFILE von JinBreen verwendet, welche Radikale und Kanji verlinkt.",
            title_audio: "Audio Dateien",
            content_audio:
                "Unsere Audio Dateien wurden von zwei Quellen zusammengefasst, welche beider unter der <license>CC BY 4.0</license> Lizenz stehen.<br/><br/>" +
                "Die Audio Dateien mit dem Label 'tofugu' werden von <wanikani>Wanikani & Tofugu</wanikani> bereitgestellt und können <audio>hier</audio> gefunden werden.<br/><br/>" +
                "Die Audio Dateien mit dem Label 'kanjialive' werden vom <kanjialive>Kanji alive Projekt</kanjialive> bereitgestellt.",
            title_sentences: "Sätze",
            content_sentences:
                "Sätze mit dem Tag 'T' wurden von <tatoeba>Tatoeba</tatoeba> bereigestellt und stehen unter den Lizenzen Creative Commons CC 1.0 & 2.0.<br/><br/>" +
                "Sätze mit dem Tag 'K' wurden direkt vom Autor von <kevin>Kevin Goes to Japan</kevin> bereitgestellt.",
            title_anim: "Kanji Animationen",
            content_anim:
                "Die zugrunde liegenden Daten für Kanji Animationen wurden von <anim>KanjiVG</anim> veröffentlicht - Einem Projekt von Ulrich Apel.",
            title_jlpt: "JLPT Informationen",
            content_jlpt: "Daten über <jlpt>JLPT-Stufen</jlpt> wurden von Jonathan Waller bereitgestellt.",
            title_token: "Wörter-Tokenisierung",
            content_token:
                "Die <token>Wort-Tokenisierung</token> wurde durch ein Projekt von Hideki Yamane ermöglicht, welches der Implementierung von Japanisch-Morphologischen Analysen dient.",
            title_pitch: "Tonhöhen-Akzente",
            content_pitch: "Tonhöhen-Akzent-Daten wurden aus dem <unidic>UniDic</unidic> extrahiert.",
            title_furigana: "Furigana",
            content_furigana:
                "Furigana für Wörter und Namen werden vom <jmdictfurigana>JmdictFurigana</jmdictfurigana> Projekt bereitgestellt.",
        },
        info: {
            shortcuts: {
                title: "Shortcuts",
                description: "Diese Shortcuts können überall benutzt werden, wenn kein Input-Feld im Fokus liegt.",
                shortcuts: {
                    global: {
                        title: "Global",
                        wsnk: "Setze die Suchkategorie auf Wörter | Sätze | Namen | Kanji",
                        slash: "Fokusiere die Suchleiste",
                    },
                    words: {
                        title: "Wörter",
                        p: "Spiele die erste Audio auf dieser Seite ab",
                    },
                },
            },
            searchbarShortcuts: {
                title: "Suchleisten-Shortcuts",
                description: "Diese Shortcuts können benutzt werden, wenn die Suchleiste im Fokus liegt.",
                shortcuts: {
                    arrowsUpDown: "Wechsle einen Vorschlag herauf | runter",
                    tab: "Welche einen Vorschlag nach unten",
                    enter: "Suche für den aktuellen Vorschlag, wenn einer ausgewählt wurde. Ansonsten suche nach dem aktuellen Input",
                },
            },
            radicalSearch: {
                title: "Radikal-Search",
                description: "Verwende Kanji, Kana oder Romaji, um nach Radikalen zu suchen.",
                explanations: {
                    kanji: {
                        title: "Kanji",
                        description: "Zeigt alle Radikale, aus denen sich das gegebene Kanji zusammensetzt",
                    },
                    kana: {
                        title: "Kana",
                        description: "Zeigt alle Radikale, welche in passenden Wörtern enthalten sind",
                    },
                    romaji: {
                        title: "Romaji",
                        description:
                            "Versucht Radikale mit dem gegebenen Namen zu finden. Ansonsten wird versucht, passende Wörter zu finden.",
                    },
                },
            },
            hashtags: {
                title: "Hashtags",
                description: "Diese Hashtags haben einen direkten Einfluss auf die Webseite.",
                headers: {
                    hashtag: "Hashtag",
                    description: "Beschreibung",
                    types: "Unterstützte Kategorien",
                },
                explanations: {
                    word: "Suche in der [Wörter]-Kategorie",
                    sentence: "Suche in der [Sätze]-Kategorie",
                    name: "Suche in der [Namen]-Kategorie",
                    kanji: "Suche in der [Kanji]-Kategorie",
                    hidden: "Verstecke alle Übersetzungen",
                },
                allTypes: "Alle Kateogrien",
            },
            filterHashtags: {
                title: "Filter-Hashtags",
                description: "Diese Hashtags filtern die Ergebnisse.",
            },
        },
    },
    paginator: {
        first: "Anfang",
        last: "Ende",
    },
    notifications: {
        title: "Informationen",
        no_notifications: "Keine neuen Benachrichtigungen",
        show: "Mehr Infos",
        close: "Schließen",
    },
    footer: {
        text: 'Jotoba würde ohne die Hilfe von vielen Open-Source Quellen nicht existieren.<br/>Besuche unsere <a href="/about" aria-label="about us">"Über Uns" - Seite</a> für eine Liste aller Mitwirkenden an diesem Projekt.',
        trello: "Trello",
        discord: "Discord",
        instagram: "Instagram",
        donations: "PayPal <ex>Donations werden immer zwischen allen Entwicklern aufgeteilt!</ex>",
    },
    toast: {
        direct_reference_copied: "Direkter Link in die Zwischenablage kopiert",
        furigana_copied: "Furigana kopiert",
        audio_copied: "Audio kopiert",
        url_copied: "Link kopiert",
    },
    message_pages: {
        default_error: {
            message: "Joto scheint gerade schwer am Arbeiten zu sein.",
            highlight: "Versuche es später nochmal!",
        },
        no_result: {
            message: "Deine Suche hat leider keine Ergebnisse ergeben.",
            message_alt: "Deine Suche hat leider keine Ergebnisse ergeben. Versuche es doch einmal hier:",
            highlight: "Versuche eine andere Eingabe!",
        },
        no_internet: {
            message: "Verbindung getrennt",
            highlight: "Verbinde dich mit dem Internet und versuche es erneut.",
        },
        "303": {
            reason: "See Other",
            hint: "Sollte es sich hierbei um einen Fehler handeln, erstelle ein Issue auf unserem GitHub",
        },
        "400": {
            reason: "Bad Request",
            hint: "Sollte es sich hierbei um einen Fehler handeln, erstelle ein Issue auf unserem GitHub",
        },
        "401": {
            reason: "Nicht Autorisiert",
            hint: "Sollte es sich hierbei um einen Fehler handeln, erstelle ein Issue auf unserem GitHub",
        },
        "404": {
            reason: "Die Seite wurde nicht gefunden.",
            hint: "Sollte es sich hierbei um einen Fehler handeln, erstelle ein Issue auf unserem GitHub",
        },
        "408": {
            reason: "Request Timeout",
            hint: "Sollte es sich hierbei um einen Fehler handeln, erstelle ein Issue auf unserem GitHub",
        },
        unknownCode: {
            reason: "Ein Fehler ist aufgetreten",
            hint: "Sollte dieser bestehen bleiben, erstelle ein Issue auf unserem GitHub",
        },
        jotoba: {
            header: "Gotcha!",
            highlight: "We knew you'd be curious about our name!",
            message:
                '<jotoba>Jotoba</jotoba> is not a real word. It is derived from <kotoba /> where the "K" was replaced by a "J" which stands for "Japanese".',
        },
    },
};
