import { LanguageCode } from "@/JotoKit/ts/common";
import { Translation } from "@/JotoKit/ts/translations";

export const TRANSLATIONS_DE: Translation = {
    lang_value: LanguageCode.German,
    lang_names: {
        "en-US": "Englisch",
        "de-DE": "Deutsch",
        "es-ES": "Spanisch",
        "fr-FR": "Französisch",
        "nl-NL": "Niederländisch",
        "sv-SE": "Schwedisch",
        ru: "Russisch",
        hu: "Ungarisch",
        "sl-SI": "Slovenisch",
        "ja-JP": "Japanisch",
    },
    searchbar: {
        placeholder: "Suchen...",
        rad_picker: {
            select_kanji: "Kanji wählen",
            search_placeholder: "Suche nach Radikalen...",
            select_kanji_placeholder: "Wähle ein Radikal die Kanji-Suche zu beginnen",
        },
        image_overlay: {
            select: "Wähle ein Bild",
            picture: "Mache ein neues Bild",
            error: "Konnte keinen Text finden!",
        },
        voice_overlay: {
            start: "Tippe zum starten",
            stop: "Tippe zum beenden",
            listening: "Wartet auf Sprachende",
            not_listening: "Wartet auf Startsignal",
            perm_denied: "Mikrofon-Berechtigung konnte nicht erlangt werden. Bitte schalte sie manuell frei, wenn nötig!",
        },
        categories: {
            words: "Wörter",
            kanji: "Kanji",
            sentences: "Sätze",
            names: "Namen",
        },
    },
    navbar: {
        title: {
            settings: "Einstellungen",
            links: "Links",
        },
        action_button: {
            language: "Sprache",
            search: "Suche",
            display: "Darstellung",
            qol: "Bedienung",
            privacy: "Privatsphäre",
            github: "Github",
            donation: "Spenden",
            discord: "Discord",
            instagram: "Instagram",
            about: "Über uns",
            help: "Hilfe",
            news: "News",
        },
        nav_button: {
            home: "Hauptmenü",
            back: "Zurück",
            exit: "App beenden",
        },
    },
    settings: {
        language: {
            title_language: "Spracheinstellungen",
            title_langSelect: "Sprachauswahl",
            select_search: "Sprache für Suchanfragen",
            select_page: "Sprache der Anwendung",
            title_ordering: "Einordnung",
            checkbox_alwaysEnglish: "Zeige immer englische Ergebnisse",
            checkbox_englishOnTop: "Zeige englische Ergebnisse als Erstes",
        },
        search: {
            title_words: "Wörter",
            checkbox_showExampleSentences: "Zeige Beispielsätze",
            checkbox_showKanjiBubbles: "Zeige Kanji",
            checkbox_showKanjiTranslation: "Zeige Kanji-Übersetzung",
            title_sentences: "Sätze",
            checkbox_showFuri: "Zeige Furigana",
            checkbox_hideTranslation: "Verstecke Übersetzung",
            title_kanji: "Kanji-Suche",
            anim_speed: "Animationsgeschwindigkeit",
            show_other_langs: "zeige weitere Sprachen",
            show_kanji: "Zeige Kanji beim Laden",
            show_numbers: "Zeige Reihenfolge mit Nummern an",
        },
        display: {
            title_user_pref: "Nutzer-Präferenzen",
            title_theme: "Farbschema",
            option_auto: "Automatisch",
            option_dark: "Dunkel",
            option_light: "Hell",
            title_jlpt: "JLPT-Level",
            n5: "N5",
            n4: "N4",
            n3: "N3",
            n2: "N2",
            n1: "N1",
            title_itemsPerPage: "Seiteneinträge",
            words_per_page: "Wörter pro Seite",
            kanji_per_page: "Kanji pro Seite",
            names_per_page: "Namen pro Seite",
            sentences_per_page: "Sätze pro Seite",
        },
        qol: {
            title_search: "Suchleiste",
            checkbox_search_anim: "Zeige Inputbeispiele",
            checkbox_index_keyboard: "Beende die App beim schließen des Index-Keyboards",
            checkbox_focusAfterSearch: "Fokussiere Suchleiste nach einer Suche",
            checkbox_focusInputAfterSearch: "Markiere Input nach einer Suche",
            title_other: "Sonstiges",
            checkbox_use_japanese_fonts: "Verwende ausgewählte japanische Schriftarten",
            checkbox_enable_furi_copy: "Aktiviere Furigana-Copy",
        },
        privacy: {
            title_privacy: "Privatsphäre",
            allow_cookie: "Erlaube das Sammeln von Nutzerdaten",
            explanation:
                "Um Jotoba zu verbessern, sammeln wir vollständig anonymisierte Daten zur Webseitennutzung. Du kannst jedoch jederzeit aus der Sammlung aussteigen.",
        },
    },
    pages: {
        loader_messages: {
            0: "Zähle Wörter",
            1: "Zeichne Kanji",
            2: "Zähle bis unendlich",
            3: "Plane neue Features",
            4: "Bereite Popcorn zu",
            5: "Zähle einfach bis 10",
            6: "Suche das Wifi-Kabel",
            7: "Beweise P=NP",
            8: "Füge zufällige Rechtschreipfehler hinzu",
            9: "Stecke das W-LAN Kabel ein",
            10: "Mit Premium geht's schneller",
            11: "Behalte alle Einsen und entferne alle Nullen",
            12: "Bitte holt mich hir raus",
            13: "Erfinde weitere Lade-Nachrichten",
            14: "Übersetze 「よろしく」",
        },
        index: {
            search: "Suchen",
            radicals: "Radikale",
            misc_links: {
                tour_text: "Neu hier? Mach doch eine kleine Tour!",
                tour_link: "Tour starten",
            },
            /* TODO: Remove. Temporary content */
            popup_news: {
                title: "Jotoba gibt es jetzt auch für Android!",
                content: "Downloade sie jetzt in Google Play",
            },
        },
        words: {
            common: "Häufiges Wort",
            jlpt: "JLPT N",
            audio: {
                tofugu: "Tofugu",
                kanjialive: "Kanji alive",
            },
            number: "{{query}} is {{number}}",
            inflection: "Wir haben die folgende Flexion für {{query}} (<word>{{word}}</word>) erkannt:",
            inflections: "Wir haben die folgenden Flexionen für {{query}} (<word>{{word}}</word>) erkannt:",
            sentence_show: "Zeige Beispielsatz",
            sentence_hide: "Verstecke Beispielsatz",
            garaigo: "Wasei, {{language}} -> {{word}}",
            pitches: "Tonhöhenakzente",
            other_forms: "Andere Formen",
            three_dot: {
                show_collocations: "Zeige Kollokationen",
                show_conjugations: "Zeige Konjugationen",
                suffix_transitivity: "Wort",
                sentence_search: "Satz-Suche",
                download_audio_tofugu: "Tofugu Audio",
                download_audio_kanjialive: "Kanjialive Audio",
                edit: "Bearbeiten",
                direct_reference: "Details",
            },
            xref: "Siehe auch <word/>",
            pos: {
                Noun: {
                    Normal: "Nomen",
                    Adverbial: "Adverbialnomen",
                    Prefix: "Präfix (Nomen)",
                    Suffix: "Suffix (Nomen)",
                    Temporal: "Zeitliches Substantiv",
                },
                Adjective: {
                    PreNounVerb: "Substantiv oder Verb, das ein Substantiv beschreibt",
                    Keiyoushi: "Ich Adjektiv",
                    KeiyoushiYoiIi: "Ich Adjectiv (Als いい konjugiert)",
                    Ku: "Ku-Adjektiv",
                    Na: "Na-Adjektiv",
                    Nari: "Formale Form vom Na-Adjektiv",
                    No: "No-Adjektiv",
                    PreNoun: "Vornomen Adjektiv",
                    Shiku: "Shiku-Adjektiv",
                    Taru: "Taru-Adjektiv",
                },
                Verb: {
                    Unspecified: "Unspezifiziertes Verb",
                    Intransitive: "Intransitives Verb",
                    Transitive: "Transitives Verb",
                    Ichidan: "Ichidan-Verb",
                    IchidanZuru: 'Ichidan "zuru"-Verb',
                    IchidanKureru: 'Ichidan "kureru"-Verb',
                    Kuru: "Kuru-Verb",
                    Nidan: {
                        class: {
                            Upper: "Oberes Nidan-Verb",
                            Lower: "Unteres Nidan-Verb",
                        },
                    },
                    Yodan: {
                        Bu: "Yodan Verb",
                        Dzu: "Yodan Verb",
                        Gu: "Yodan Verb",
                        Hu: "Yodan Verb",
                        Ku: "Yodan Verb",
                        Mu: "Yodan Verb",
                        Nu: "Yodan Verb",
                        Ru: "Yodan Verb",
                        Su: "Yodan Verb",
                        Tsu: "Yodan TVerb",
                        U: "Yodan Verb",
                        Yu: "Yodan Verb",
                        Zu: "Yodan Verb",
                    },
                    Godan: {
                        Bu: "Godan Verb",
                        Gu: "Godan Verb",
                        Ku: "Godan Verb",
                        Mu: "Godan Verb",
                        Nu: "Godan Verb",
                        Ru: "Godan Verb",
                        Su: "Godan Verb",
                        Tsu: "Godan Verb",
                        U: "Godan Verb",
                        Aru: "Godan Verb",
                        USpecial: "Godan Verb (Speziell)",
                        Uru: "Godan Verb",
                        RuIrreg: "Godan Verb (ungregelmäßig)",
                        IkuYuku: "Godan Verb",
                    },
                    Irregular: {
                        Nu: "Unregelmäßiges Verb",
                        Ru: "Unregelmäßiges Verb",
                        Su: "Unregelmäßiges Verb",
                        NounOrAuxSuru: 'Substantiv mit "suru"',
                        Suru: "Suru-Verb",
                        SuruSpecial: "Speziales Suru",
                    },
                },
                Sfx: "SoundFx",
                Expr: "Ausdruck",
                Counter: "Zähler",
                Suffix: "Suffix",
                Prefix: "Präfix",
                Particle: "Partikel",
                Interjection: "Zwischenruf",
                Pronoun: "Pronomen",
                Numeric: "Numerisch",
                Adverb: "Adverb",
                AdverbTo: "To-Adverb",
                Auxilary: "Hilfsmittel",
                AuxilaryAdj: "Hilfsadjektiv",
                AuxilaryVerb: "Hilfsverb",
                Conjunction: "Konjugation",
                Unclassified: "Nicht klassifiziert",
            },
            word_class: {
                PreNoun: "Vornomen",
                Noun: "Nomen",
                Pronoun: "Pronomen",
                Adjective: "Adjektiv",
                Verb: "Verb",
                Adverb: "Adverb",
                Particle: "Partikel",
                Interjection: "Zwischenruf",
                Symbol: "Symbol",
                Conjunction: "Verbindung",
                Suffix: "Suffix",
                Prefix: "Präfix",
                Space: "Leerzeichen",
                Expr: "Ausdruck",
            },
            field: {
                term: "Begriff",
                Agriculture: "Landwirtschaft",
                Anatomy: "Anatomie",
                Archeology: "Archäologie",
                Architecture: "Architektur",
                ArtAesthetics: "Kunstästhetik",
                Astronomy: "Astronomie",
                AudioVisual: "Audiovisuell",
                Aviation: "Luftfahrt",
                Baseball: "Baseball",
                Biochemistry: "Biochemie",
                Biology: "Biologie",
                Botany: "Botanik",
                Buddhism: "Buddhismus",
                Business: "Business",
                Chemistry: "Chemie",
                Christianity: "Christentum",
                Computing: "Computer",
                Clothing: "Kleidung",
                Crystallography: "Kristallographie",
                Ecology: "Ökologie",
                Economics: "Wirtschaft",
                Electricity: "Elektrizität",
                Electronics: "Elektronik",
                Embryology: "Embryologie",
                Engineering: "Ingenieurwesen",
                Entomology: "Entomologie",
                Finance: "Finanzen",
                Fishing: "Fischerei",
                FoodCooking: "Koch",
                Gardening: "Gärtnerei",
                Genetics: "Genetik",
                Geography: "Geografie",
                Geology: "Geologie",
                Geometry: "Geometrie",
                GoGame: "Go (game)",
                Golf: "Golf",
                Grammar: "Grammatik",
                GreekMythology: "Griechische Mythologie",
                Hanafuda: "Hanafuda",
                Horseracing: "Pferderennen",
                Law: "Recht",
                Linguistics: "Linguistik",
                Logic: "Logik",
                MartialArts: "Martial Arts",
                Mahjong: "Mahjong",
                Mathematics: "Mathemaik",
                MechanicalEngineering: "Maschinenbau",
                Medicine: "Medizin",
                ClimateWeather: "Klima / Wetter",
                Military: "Militär",
                Music: "Musik",
                Ornithology: "Vogelkunde",
                Paleontology: "Paläontologie",
                Pathology: "Pathologie",
                Pharmacy: "Pharmazie",
                Philosophy: "Philosophie",
                Photography: "Fotografie",
                Physics: "Physik",
                Physiology: "Physiologie",
                Printing: "Druckerei",
                Psychitatry: "Psychatrie",
                Shinto: "Shinto",
                Railway: "Eisenbahn",
                Shogi: "Shogi",
                Sports: "Sports",
                Statistics: "Statistik",
                Sumo: "Sumo",
                Telecommunications: "Telekommunikation",
                Trademark: "Trademark",
                Videogame: "Videospiel",
                Zoology: "Zoologie",
                Cards: "Karten",
                Dentistry: "Zahnmedizin",
                Kabuki: "Kabuki",
                Politics: "Politik",
                Psychology: "Psychologie",
            },
            misc: {
                Abbreviation: "Abkürzung",
                Archaism: "Archaismus",
                Character: "Charakter",
                ChildrensLanguage: "Kindersprache",
                Colloquialism: "Umgangssprache",
                CompanyName: "Firmenname",
                Creature: "Kreatur",
                DatedTerm: "Datierter Begriff",
                Deity: "Gottheit",
                Derogatory: "Abwertend",
                Document: "Dokument",
                Event: "Event",
                FamiliarLanguage: "Vertraute Sprache",
                FemaleTermOrLanguage: "Weblicher Begriff/Sprache",
                Fiction: "Fiktion",
                GivenName: "Vorname",
                Group: "Gruppe",
                HistoricalTerm: "Historischer Begriff",
                HonorificLanguage: "Höfliche Sprache",
                HumbleLanguage: "Bescheidene Sprache",
                IdiomaticExpression: "Idiomatischer Ausdruck",
                JocularHumorousTerm: "Scherzhafter humoristischer Begriff",
                Legend: "Legende",
                LiteraryOrFormalTerm: "Literarischer/formeller Begriff",
                MangaSlang: "Manga-Slang",
                MaleTermOrLanguage: "Männlicher Begriff/Sprache",
                Mythology: "Mythologie",
                InternetSlang: "Internet-Slang",
                Object: "Objekt",
                ObsoleteTerm: "Veralteter Begriff",
                ObscureTerm: "Unbekannter Begriff",
                OnomatopoeicOrMimeticWord: "Onomatopoetisches oder mimetisches Wort",
                OrganizationName: "Organisationsname",
                Other: "Andere",
                Personname: "Personenname",
                PlaceName: "Ortsname",
                PoeticalTerm: "Poetischer Begriff",
                PoliteLanguage: "Höfliche Sprache",
                ProductName: "Produktname",
                Proverb: "Sprichwort",
                Quotation: "Zitat",
                Rare: "Selten",
                Religion: "Religion",
                Sensitive: "Sensibel",
                Service: "Service",
                Slang: "Slang",
                RailwayStation: "Bahnhof",
                FamilyOrSurname: "Familien- oder Nachname",
                UsuallyWrittenInKana: "Üblicherweise in Kana geschrieben",
                UnclassifiedName: "Nicht klassifizierter Name",
                VulgarExpressionOrWord: "Vulgärer Ausdruck/Wort",
                ArtWork: "Kunstwerk",
                RudeOrXRatedTerm: "Nicht Jugendfreier Begriff",
                Yojijukugo: "Yojijukugo",
                Euphemistic: "Euphemistisch",
            },
        },
        kanji: {
            strokes: "{{stroke_count}} Striche",
            jlpt: "JLPT N{{jlpt}}",
            grade: "Beigebracht in der {{grade}}. Klasse",
            radical: "Radikal:",
            parts: "Teile:",
            kun: "Kun:",
            on: "On:",
            title_kun: "Kunyomi",
            title_on: "Onyomi",
            tooltip_jouyou: "Jouyou Kanji",
            tooltip_kokuji: "Kokuji Kanji",
            tooltip_stroke: "Anzahl der Striche",
            tooltip_grade: "Beigebracht in dieser Klasse",
            tooltip_jlpt: "JLPT-Level",
            tooltip_frequency: "Rang der Häufigkeit in Zeitschriften aus 2500",
            similar_kanji: "Similar:",
            reading_chinese: "Chinesisch:",
            reading_korean: "Koreanisch:",
            reading_vietnamese: "Vietnamesisch:",
            anim_reset: "Zurücksetzen",
        },
        names: {
            full_name: "Name",
            sex: "Geschlecht",
            origin: "Herkunft",
        },
        sentences: {
            source_kevin: "Kevin Goes to Japan",
            source_tatoeba: "Tatoeba",
            sentence_show: "[Zeigen]",
            sentence_hide: "[Verstecken]",
            three_dot: {
                sentence_search: "Wortsuche",
                tatoeba_search: "In Tatoeba anzeigen",
                direct_reference: "Details",
            },
        },
        details: {
            common: {
                share: "Teilen",
            },
            tabs: {
                word: "Wort",
                words: "Wörter",
                kanji: "Kanji",
                sentenceTl: "Übersetzung",
                sentences: "Sätze",
                collocations: "Kollokationen",
                conjugations: "Konjugationen",
                more: "Mehr",
            },
            sentences: {
                source_kevin: "Kevin Goes to Japan",
                source_tatoeba: "Tatoeba",
            },
            words: {
                conjugations: {
                    affirmative: "Positiv",
                    negative: "Negativ",
                    present: "Gegenwart",
                    present_polite: "Gegenwart (nett)",
                    past: "Vergangenheit",
                    past_polite: "Vergangenheit (nett)",
                    te_form: "Te-Form",
                    potential: "Potenzial",
                    passive: "Passiv",
                    causative: "Kausativ",
                    causative_passive: "Kausativ (Passiv)",
                    imperative: "Imperativ",
                    ba: "Ba",
                    tara: "Tara",
                    zu: "Zu",
                },
                audio: {
                    tofugu: "Tofugu",
                    kanjialive: "Kanji alive",
                },
                switch: "Wechsel zu {{pair}}",
                Transitive: "Transitiv",
                Intransitive: "Intransitiv",
                jlpt: "JLPT-Level",
                frequency: "Häufigkeit",
                edit: "Bearbeiten",
            },
        },
        tour: {
            title_dropdown: "Fortgeschrittene Suche",
            description_dropdown:
                "Suche nach <g>Wörtern, Kanjis, Sätzen</g> oder <g>Namen</g> indem du das <g>drop down Men&uuml;</g> neben der Suchbar betätigst.<br/><br/>Du kannst jedoch auch <kbd>w</kbd> <kbd>k</kbd> <kbd>s</kbd> und <kbd>n</kbd> auf deiner <g>Tastatur</g> dafür benutzen.",
            description_dropdown_mobile:
                "Suche nach <g>Wörtern, Kanjis, Sätzen</g> oder <g>Namen</g> indem du den <g>Pfeil nach Oben</g> in der Suchbar drückst.",
            title_multilang: "Mehrsprachige Suche",
            description_multilang:
                "Du kannst eine <g>weitere Sprache</g>, z.B Deutsch, in den <g>Einstellungen</g> hinzufügen um <g>&Uuml;bersetzungen auf Deutsch</g> zu sehen.",
            title_sentencereader: "Japanische Lesehilfe",
            description_sentencereader:
                "Du kannst einen <g>ganzen Japanischen Satz</g> eingeben um ihn in seine <g>einzelnen Wörter</g> aufteilen zu lassen.<br/><br/>Mit dem <g>grünen Stift</g> kannst du dir die Aufteilungen <g>anpassen</g> indem du auf die <g>Leerzeichen</g> oder <g>Spalten</g> zwischen den <g>Buchstaben</g> klickst.",
            title_3dot: "3-dot Menü",
            title_3dot_mobile: "Details Seite",
            description_3dot:
                "W&auml;hle das <g>3-dot Men&uuml;</g> auf einer Such-seite aus um Zugriff zu <g>weiteren Features</g> zu bekommen, wie <g>direkte Links</g>, <g>in/transitive Versionen</g>, <g>Satz-suche</g> und viel mehr.",
            description_3dot_mobile:
                "<g>Klicke</g> auf ein Wort in den <g>Suchergebnissen</g> um mehr <g>Informationen</g> zu sehen, wie z.B die <g>in/transitive Version</g>, <g>Kanjis</g>, <g>Beispiels&auml;tze</g> und viel mehr.",
            title_kanjigraphs: "Kanji Aufteilungen",
            description_kanjigraphs:
                "Klicke auf ein <g>Kanji Literal</g> auf der Kanji Such Seite um zu sehen, wie es <g>aufgebaut</g> wird.<br/><br/>Mit dem Knopf <g>unten rechts</g> kannst du zwischen der <g>detaillierten</g> und der <g>standart Ansicht</g> wechseln.",
            action_next: "Weiter",
            action_get_started: "Los geht's",
            action_previous: "Zurück",
        },
        bookmarks: {
            undo: "Rückgängig",
            no_content:
                "<b>Du hast noch keine Vermerke.</b><br/><br/>Suche nach einem Wort, klicke es an und du kannst das Wort über das Icon in der oberen, linken Ecke hinzufügen!",
        },
        about: {
            title_about: "Über uns",
            content_about:
                "Jotoba ist ein mehrsprachiges Japanisch-Wörterbuch, das auf zahlreichen kostenlosen Ressourcen aus dem Internet aufbaut. Es bietet viele praktische Tools zum Nachschlagen von Wörtern, Kanji, Beispielsätzen, japanischen Namen und vielem mehr. " +
                "Auf dieser Seite möchten wir allen danken, die solch wunderbare Ressourcen erstellen und etwas wie Jotoba überhaupt möglich machen.<br/><br/>" +
                "Wenn du dich für die Entwicklung von Jotoba interessierst, schau doch einmal auf unserem <trello>Trello Board</trello> vorbei. Dort kannst du sehen, woran wir derzeit arbeiten und welche Funktionen in zukünftigen Versionen kommen werden!",
            dev_preview_frontend: "Frontend",
            dev_preview_backend: "Backend",
            title_jotoKun: "Joto-kun",
            content_jotoKun:
                "Joto-kun wurde von einer guten Freundin erstellt, welche eine wahrere Zauberin ist, wenn es ums Designen geht!",
            title_wkn: "Wörter & Kanji & Namen",
            content_wkn:
                "Diese Website verwendet die Wörterbuchdateien <jmdict>JMdict</jmdict>, <kanjidic>KANJIDIC2</kanjidic>, <kradfile>KRADFILE</kradfile> und <jmnedict>JMnedict</jmnedict>. " +
                "Diese Dateien sind Eigentum der <edrdg>Electronic Dictionary Research and Development Group</edrdg> und werden gemäß ihrer <license>Lizenz</license> verwendet.",
            title_audio: "Audio Dateien",
            content_audio:
                "Audiodateien mit dem Label 'Tofugu' werden von <tofugu>Tofugus</tofugu> Kanji- und Vokabellernwebsite <wanikani>WaniKani</wanikani> zur Verfügung gestellt und stehen unter der Lizenz <license>Creative Commons Attribution Share Alike 4.0</license>. " +
                "Sie können <audio>hier</audio> gefunden werden.<br/><br/>" +
                "Audiodateien mit dem Label 'Kanjialive' werden vom <kanjialive>Kanji Alive Projekt</kanjialive> zur Verfügung gestellt und stehen unter der Lizenz <kalicense>Creative Commons CC BY 4.0</kalicense>. Sie können <kasource>hier</kasource> gefunden werden.",
            title_sentences: "Sätze",
            content_sentences:
                "Beispielsätze mit dem Tag 'T' stammen von <tatoeba>Tatoeba</tatoeba> und sind lizenziert unter <license>Creative Commons CC BY 2.0 FR</license>. Sie basieren auf dem Tanaka-Korpus von Professor Yasuhito Tanaka. " +
                "Beispielsätze in der Wort-Suche stammen ebenfalls aus dem Tanaka-Korpus." +
                "<br/><br/>" +
                "Beispielsätze mit dem Tag 'K' werden direkt von der Autorin von <kevin>Kevin Goes to Japan</kevin> bereitgestellt.",
            title_anim: "Kanji-Strichreihenfolgen",
            content_anim:
                "Informationen zur Strichreihenfolge der Kanjis stammen von <anim>KanjiVG</anim>, das urheberrechtlich © 2009-2023 Ulrich Apel geschützt und unter <license>Creative Commons Attribution-Share Alike 3.0</license> lizenziert ist." +
                "<br/><br/>" +
                "Um diese Daten in SVGs umzuwandeln, haben wir eine von uns <altversion>veränderte Version</altversion> von dem <kanjivgsvg>kanjivg2svg</kanjivgsvg>-Projekt von Kim Ahlström verwendet, welches unter der <licenseKim>Creative Commons Attribution-Share Alike 3.0</licenseKim> Lizenz lizenziert ist.",
            title_jlpt: "JLPT Informationen",
            content_jlpt:
                "Daten über JLPT-Stufen werden von <jw>Jonathan Waller's</jw> <jlpt>Ressourcen</jlpt> bereitgestellt, welche der <license>Creative Commons CC BY</license> Lizenz unterliegen.",
            title_furigana: "Furigana",
            content_furigana:
                "Furigana für Wörter und Namen werden von dem <jmdictfurigana>JmdictFurigana</jmdictfurigana> Projekt bereitgestellt und haben die gleiche Lizenz wie das JMdict (<license>Creative Commons Attribution-ShareAlike</license>).",
        },
        info: {
            tour: {
                title: "Tour",
                description: "-> <link>Mach ne kleine tour</link> um die wichtigsten Features von Jotoba kennenzulernen",
            },
            shortcuts: {
                title: "Shortcuts",
                description: "Diese Shortcuts können überall benutzt werden, wenn kein Input-Feld im Fokus liegt.",
                shortcuts: {
                    global: {
                        title: "Global",
                        wsnk: "Setze die Suchkategorie auf Wörter | Sätze | Namen | Kanji",
                        slash: "Fokusiere die Suchleiste",
                    },
                    words: {
                        title: "Wörter",
                        p: "Spiele die erste Audio auf dieser Seite ab",
                    },
                },
            },
            searchbarShortcuts: {
                title: "Suchleisten-Shortcuts",
                description: "Diese Shortcuts können benutzt werden, wenn die Suchleiste im Fokus liegt.",
                shortcuts: {
                    arrowsUpDown: "Wechsle einen Vorschlag herauf | runter",
                    tab: "Welche einen Vorschlag nach unten",
                    enter: "Suche für den aktuellen Vorschlag, wenn einer ausgewählt wurde. Ansonsten suche nach dem aktuellen Input",
                },
            },
            radicalSearch: {
                title: "Radikal-Search",
                description: "Verwende Kanji, Kana oder Romaji, um nach Radikalen zu suchen.",
                explanations: {
                    kanji: {
                        title: "Kanji",
                        description: "Zeigt alle Radikale, aus denen sich das gegebene Kanji zusammensetzt",
                    },
                    kana: {
                        title: "Kana",
                        description: "Zeigt alle Radikale, welche in passenden Wörtern enthalten sind",
                    },
                    romaji: {
                        title: "Romaji",
                        description:
                            "Versucht Radikale mit dem gegebenen Namen zu finden. Ansonsten wird versucht, passende Wörter zu finden.",
                    },
                },
            },
            hashtags: {
                title: "Hashtags",
                description: "Diese Hashtags haben einen direkten Einfluss auf die Webseite.",
                headers: {
                    hashtag: "Hashtag",
                    description: "Beschreibung",
                    types: "Unterstützte Kategorien",
                },
                explanations: {
                    word: "Suche in der [Wörter]-Kategorie",
                    sentence: "Suche in der [Sätze]-Kategorie",
                    name: "Suche in der [Namen]-Kategorie",
                    kanji: "Suche in der [Kanji]-Kategorie",
                    hidden: "Verstecke alle Übersetzungen",
                },
                allTypes: "Alle Kateogrien",
            },
            filterHashtags: {
                title: "Filter-Hashtags",
                description: "Diese Hashtags filtern die Ergebnisse.",
            },
        },
    },
    paginator: {
        first: "Anfang",
        last: "Ende",
    },
    login: {
        email: "E-Mail",
        username: "Nutzername",
        password: "Passwort",
        login: "Login",
        register: "Register",
        logout: "Logout",
        not_registered: "Noch nicht registriert?",
        already_registered: "Bereits registered?",
        sign_in: "Login",
        create_account: "Account erstellen",
        login_success: "Login erfolgreich",
        register_success: "Registrierung erfolgreich",
        logout_success: "Abgemeldet",
    },
    notifications: {
        title: "Informationen",
        no_notifications: "Keine neuen Benachrichtigungen",
        show: "Mehr Infos",
        close: "Schließen",
    },
    footer: {
        socials: "Socials",
        trello: "Trello",
        discord: "Discord",
        instagram: "Instagram",
        reddit: "Reddit",
        support_us: "Unterstütze uns",
        donations: "PayPal <ex>Donations werden immer zwischen allen Entwicklern aufgeteilt!</ex>",
        credits_title: "Über uns",
        credits:
            "Jotoba verwendet viele verschiedene freie Daten. Ein Paar der Größten davon sind <jmdict>JMdict</jmdict>, <kanjidic>KANJIDIC2</kanjidic>, <kradfile>RADKFILE/KRADFILE</kradfile> und <jmnedict>JMnedict</jmnedict>, welche Eigentum der <edrdg>Electronic Dictionary Research and Development Group</edrdg> sind und entsprechend ihrer <license>Lizenz</license> verwendet werden.",
        credits_about: 'Besuche unsere <about>"Über Uns" - Seite</about> für eine Liste aller verwendeten Datenquellen in diesem Projekt.',
        links_title: "Links",
        about: "Über uns",
        applink: "Android App",
        privacy: "Datenschutz",
    },
    toast: {
        direct_reference_copied: "Direkter Link in die Zwischenablage kopiert",
        furigana_copied: "Furigana kopiert",
        audio_copied: "Audio kopiert",
        url_copied: "Link kopiert",
    },
    message_pages: {
        default_error: {
            message: "Joto scheint gerade schwer am Arbeiten zu sein.",
            highlight: "Versuche es später nochmal!",
        },
        no_result: {
            message: "Deine Suche hat leider keine Ergebnisse ergeben.",
            message_alt: "Deine Suche hat leider keine Ergebnisse ergeben. Versuche es doch einmal hier:",
            highlight: "Versuche eine andere Eingabe!",
        },
        no_internet: {
            message: "Verbindung getrennt",
            highlight: "Verbinde dich mit dem Internet und versuche es erneut.",
        },
        "303": {
            reason: "See Other",
            hint: "Sollte es sich hierbei um einen Fehler handeln, melde ihn auf unserem Discord",
        },
        "400": {
            reason: "Bad Request",
            hint: "Sollte es sich hierbei um einen Fehler handeln, melde ihn auf unserem Discord",
        },
        "401": {
            reason: "Nicht Autorisiert",
            hint: "Sollte es sich hierbei um einen Fehler handeln, melde ihn auf unserem Discord",
        },
        "404": {
            reason: "Die Seite wurde nicht gefunden.",
            hint: "Sollte es sich hierbei um einen Fehler handeln, melde ihn auf unserem Discord",
        },
        "408": {
            reason: "Request Timeout",
            hint: "Sollte es sich hierbei um einen Fehler handeln, melde ihn auf unserem Discord",
        },
        unknownCode: {
            reason: "Ein Fehler ist aufgetreten",
            hint: "Sollte dieser bestehen bleiben, melde ihn auf unserem Discord",
        },
        jotoba: {
            header: "Gotcha!",
            highlight: "We knew you'd be curious about our name!",
            message:
                '<jotoba>Jotoba</jotoba> is not a real word. It is derived from <kotoba /> where the "K" was replaced by a "J" which stands for "Japanese".',
        },
    },
    share: {
        title: "Diese Seite teilen",
    },
};
