import { LanguageCode } from "@/JotoKit/ts/common";
import { Translation } from "@/JotoKit/ts/translations";

export const TRANSLATIONS_EN: Translation = {
    lang_value: LanguageCode.English,
    lang_names: {
        "en-US": "English",
        "de-DE": "German",
        "es-ES": "Spanish",
        "fr-FR": "French",
        "nl-NL": "Dutch",
        "sv-SE": "Swedish",
        ru: "Russian",
        hu: "Hungarian",
        "sl-SI": "Slovenian",
        "ja-JP": "Japanese",
    },
    searchbar: {
        placeholder: "Search...",
        rad_picker: {
            select_kanji: "Select Kanji",
            search_placeholder: "Search by Kanji...",
            select_kanji_placeholder: "Pick a radical to start searching for kanji",
        },
        image_overlay: {
            select: "Select an image",
            picture: "Take a picture",
            error: "Couldn't find any text!",
        },
        voice_overlay: {
            start: "click to start recording",
            stop: "click to stop recording",
            listening: "Speak now!",
            not_listening: "Waiting to start...",
            perm_denied: "Permission request failed! Please provide the microphone permission manually if needed.",
        },
        categories: {
            words: "Words",
            kanji: "Kanji",
            sentences: "Sentences",
            names: "Names",
        },
    },
    navbar: {
        title: {
            settings: "Settings",
            links: "Links",
        },
        action_button: {
            language: "Language",
            search: "Search",
            display: "Display",
            qol: "QoL",
            privacy: "Privacy",
            github: "Github",
            donation: "Donations",
            discord: "Discord",
            instagram: "Instagram",
            about: "About",
        },
        nav_button: {
            home: "Home",
            back: "Back",
            exit: "Exit",
        },
    },
    settings: {
        language: {
            title_language: "Language settings",
            title_langSelect: "Language settings",
            select_search: "Search language",
            select_page: "UI language",
            title_ordering: "Language ordering",
            checkbox_alwaysEnglish: "Always show english results",
            checkbox_englishOnTop: "Show english results on top",
        },
        search: {
            title_words: "Words",
            checkbox_showExampleSentences: "Show example sentences",
            title_sentences: "Sentences",
            checkbox_showFuri: "Show furigana",
            title_kanji: "Kanji Page",
            show_other_langs: "Show other languages",
            show_kanji: "Show drawn Kanji on load",
            show_numbers: "Show Stroke number",
            anim_speed: "Animation Speed",
        },
        display: {
            title_theme: "Color Scheme",
            option_auto: "Automatic",
            option_dark: "Dark",
            option_light: "Light",
            title_itemsPerPage: "Page entries",
            words_per_page: "Words per Page",
            kanji_per_page: "Kanji per Page",
            names_per_page: "Names per Page",
            sentences_per_page: "Sentences per Page",
        },
        qol: {
            title_search: "Searchbar",
            checkbox_search_anim: "Enable input examples",
            checkbox_index_keyboard: "Close app along the index-keyboard",
            checkbox_focusAfterSearch: "Focus searchbar after search",
            checkbox_focusInputAfterSearch: "Select input after search",
            title_other: "Other",
            checkbox_use_japanese_fonts: "Use Jotoba's font choice",
            checkbox_enable_furi_copy: "Enable Furigana copy",
        },
        privacy: {
            title_privacy: "Privacy settings",
            allow_cookie: "Share usage statistics",
            explanation:
                "To help improve Jotoba, we collect certain anonymous data (in accordance with the GDPR) by default - but if you wish, we will stop collecting anything from you.",
        },
    },
    pages: {
        loader_messages: {
            0: "Counting words",
            1: "Drawing kanji",
            2: "Counting to infinity",
            3: "Planing new features",
            4: "Why don't you order a sandwich?",
            5: "Just count to 10",
            6: "Finding the Wifi cable",
            7: "Proving P=NP",
            8: "Adding randomly mispeled words",
            9: "TODO: Insert elevator music",
            10: "Our premium plan is faster",
            11: "Keeping all the 1's and removing all the 0's",
            12: "Help, I'm trapped in a loader!",
            13: "Adding non helpful loading messages",
            14: "Translating 「よろしく」",
        },
        index: {
            search: "Search",
            radicals: "Radicals",
        },
        words: {
            common: "common word",
            jlpt: "JLPT N",
            audio: {
                tofugu: "Tofugu",
                kanjialive: "Kanji alive",
            },
            number: "{{query}} is {{number}}",
            inflection: "{{query}} could be an inflection of <word>{{word}}</word> with this form:",
            inflections: "{{query}} could be an inflection of <word>{{word}}</word> with these forms:",
            sentence_show: "Show long example sentence",
            sentence_hide: "Hide example sentence",
            garaigo: "Wasei, {{language}} -> {{word}}",
            pitches: "Pitches",
            other_forms: "Other forms",
            three_dot: {
                show_collocations: "Show collocations",
                show_conjugations: "Show conjugations",
                suffix_transitivity: "Word",
                sentence_search: "Sentence search",
                download_audio_tofugu: "Tofugu audio",
                download_audio_kanjialive: "Kanjialive audio",
                direct_reference: "Direct reference",
            },
            pos: {
                Noun: {
                    Normal: "Noun",
                    Adverbial: "Adverbial noun",
                    Prefix: "Prefix (noun)",
                    Suffix: "Suffix (noun)",
                    Temporal: "Temporal noun",
                },
                Adjective: {
                    PreNounVerb: "Noun or verb describing a noun",
                    Keiyoushi: "I adjective",
                    KeiyoushiYoiIi: "I adjective (conjugated like いい)",
                    Ku: "Ku adjective",
                    Na: "Na adjective",
                    Nari: "Formal form of na adjective",
                    No: "No adjective",
                    PreNoun: "Pre noun adjective",
                    Shiku: "Shiku adjective",
                    Taru: "Taru adjective",
                },
                Verb: {
                    Unspecified: "Unspecified verb",
                    Intransitive: "Intransitive verb",
                    Transitive: "Transitive verb",
                    Ichidan: "Ichidan verb",
                    IchidanZuru: "Ichidan zuru verb",
                    IchidanKureru: "Ichidan kureru verb",
                    Kuru: "Kuru verb",
                    Nidan: {
                        class: {
                            Upper: "Nidan verb (upper)",
                            Lower: "Nidan verb (lower)",
                        },
                    },
                    Yodan: {
                        Bu: "Yodan Bu verb",
                        Dzu: "Yodan Dzu verb",
                        Gu: "Yodan Gu verb",
                        Hu: "Yodan Hu verb",
                        Ku: "Yodan Ku verb",
                        Mu: "Yodan Mu verb",
                        Nu: "Yodan Nu verb",
                        Ru: "Yodan Ru verb",
                        Su: "Yodan Su verb",
                        Tsu: "Yodan Tsu verb",
                        U: "Yodan U verb",
                        Yu: "Yodan YU verb",
                        Zu: "Yodan Zu verb",
                    },
                    Godan: {
                        Bu: "Godan Bu verb",
                        Gu: "Godan Gu verb",
                        Ku: "Godan Ku verb",
                        Mu: "Godan Mu erb",
                        Nu: "Godan Nu verb",
                        Ru: "Godan Ru verb",
                        Su: "Godan Su verb",
                        Tsu: "Godan Tsu verb",
                        U: "Godan U verb",
                        Aru: "Godan Aru verb",
                        USpecial: "Godan U verb (special)",
                        Uru: "Godan U verb",
                        RuIrreg: "Godan Ru verb",
                        IkuYuku: "Godan Iku verb",
                    },
                    Irregular: {
                        Nu: "Irregular verb ending in nu",
                        Ru: "Irregular verb ending in ru",
                        Su: "Irregular verb ending in su",
                        NounOrAuxSuru: "Noun taking suru",
                        Suru: "Suru verb",
                        SuruSpecial: "Suru special",
                    },
                },
                Sfx: "SoundFx",
                Expr: "Expression",
                Counter: "Counter",
                Suffix: "Suffix",
                Prefix: "Prefix",
                Particle: "Particle",
                Interjection: "Interjection",
                Pronoun: "Pronoun",
                Numeric: "Numeric",
                Adverb: "Adverb",
                AdverbTo: "To-Adverb",
                Auxilary: "Auxiliary",
                AuxilaryAdj: "Auxiliary adjective",
                AuxilaryVerb: "Auxiliary verb",
                Conjunction: "Verbindung",
                Unclassified: "Unclassified",
            },
            word_class: {
                "Pre-noun": "Pre-noun",
                Noun: "Noun",
                Pronoun: "Pronoun",
                Adjective: "Adjective",
                Verb: "Verb",
                Adverb: "Adverb",
                Particle: "Particle",
                Interjection: "Interjection",
                Symbol: "Symbol",
                Conjugation: "Conjugation",
                Suffix: "Suffix",
                Prefix: "Prefix",
                Space: "Space",
            },
            field: {
                term: "term",
                Agriculture: "Agriculture",
                Anatomy: "Anatomy",
                Archeology: "Archeology",
                Architecture: "Architecture",
                ArtAesthetics: "Art aesthetics",
                Astronomy: "Astronomy",
                AudioVisual: "Audiovisual",
                Aviation: "Aviation",
                Baseball: "Baseball",
                Biochemistry: "Biochemistry",
                Biology: "Biology",
                Botany: "Botany",
                Buddhism: "Buddhism",
                Business: "Business",
                Chemistry: "Chemistry",
                Christianity: "Christianity",
                Computing: "Computing",
                Clothing: "Clothing",
                Crystallography: "Crystallography",
                Ecology: "Ecology",
                Economics: "Economics",
                Electricity: "Electricity",
                Electronics: "Electronics",
                Embryology: "Embryology",
                Engineering: "Engineering",
                Entomology: "Entomology",
                Finance: "Finance",
                Fishing: "Fishing",
                FoodCooking: "Food cooking",
                Gardening: "Gardening",
                Genetics: "Genetics",
                Geography: "Geography",
                Geology: "Geology",
                Geometry: "Geometry",
                GoGame: "Go (game)",
                Golf: "Golf",
                Grammar: "Grammar",
                GreekMythology: "Greek Mythology",
                Hanafuda: "Hanafuda",
                Horseracing: "Horseracing",
                Law: "Law",
                Linguistics: "Linguistics",
                Logic: "Logic",
                MartialArts: "Martial Arts",
                Mahjong: "Mahjong",
                Mathematics: "Mathematics",
                MechanicalEngineering: "Mechanical engineering",
                Medicine: "Medicine",
                ClimateWeather: "Climate / Weather",
                Military: "Military",
                Music: "Music",
                Ornithology: "Ornithology",
                Paleontology: "Paleontology",
                Pathology: "Pathology",
                Pharmacy: "Pharmacy",
                Philosophy: "Philosophy",
                Photography: "Photography",
                Physics: "Physics",
                Physiology: "Physiology",
                Printing: "Printing",
                Psychitatry: "Psychitatry",
                Shinto: "Shinto",
                Railway: "Railway",
                Shogi: "Shogi",
                Sports: "Sports",
                Statistics: "Statistics",
                Sumo: "Sumo",
                Telecommunications: "Telecommunications",
                Trademark: "Trademark",
                Videogame: "Videogame",
                Zoology: "Zoology",
                Cards: "Cards",
                Dentistry: "Dentistry",
                Kabuki: "Kabuki",
                Politics: "Politics",
                Psychology: "Psychology",
            },
            misc: {
                Abbreviation: "Abbreviation",
                Archaism: "Archaism",
                Character: "Character",
                ChildrensLanguage: "Childrens language",
                Colloquialism: "Colloquialism",
                CompanyName: "Company name",
                Creature: "Creature",
                DatedTerm: "Dated term",
                Deity: "Deity",
                Derogatory: "Derogatory",
                Document: "Document",
                Event: "Event",
                FamiliarLanguage: "Familiar language",
                FemaleTermOrLanguage: "Female term/language",
                Fiction: "Fiction",
                GivenName: "Given name",
                Group: "Group",
                HistoricalTerm: "Historical term",
                HonorificLanguage: "Honorific language",
                HumbleLanguage: "Humble language",
                IdiomaticExpression: "Idiomatic expression",
                JocularHumorousTerm: "Jocular humorous term",
                Legend: "Legend",
                LiteraryOrFormalTerm: "Literary/formal term",
                MangaSlang: "Manga slang",
                MaleTermOrLanguage: "Male term/language",
                Mythology: "Mythology",
                InternetSlang: "Internet slang",
                Object: "Object",
                ObsoleteTerm: "Obsolete term",
                ObscureTerm: "Obscure term",
                OnomatopoeicOrMimeticWord: "Onomatopoeic or mimetic word",
                OrganizationName: "Organization name",
                Other: "Other",
                Personname: "Person name",
                PlaceName: "Place name",
                PoeticalTerm: "Poetical term",
                PoliteLanguage: "Polite language",
                ProductName: "Product name",
                Proverb: "Proverb",
                Quotation: "Quotation",
                Rare: "Rare",
                Religion: "Religion",
                Sensitive: "Sensitive",
                Service: "Service",
                Slang: "Slang",
                RailwayStation: "Railway station",
                FamilyOrSurname: "Family or surname",
                UsuallyWrittenInKana: "Usually written in kana",
                UnclassifiedName: "Unclassified name",
                VulgarExpressionOrWord: "Vulgar expression/word",
                ArtWork: "Artwork",
                RudeOrXRatedTerm: "Rude/x-rated term",
                Yojijukugo: "Yojijukugo",
                Euphemistic: "Euphemistic",
            },
        },
        kanji: {
            strokes: "{{stroke_count}} strokes",
            jlpt: "JLPT N{{jlpt}}",
            grade: "Taught in {{grade}}. grade",
            radical: "Radical:",
            parts: "Parts:",
            kun: "Kun:",
            on: "On:",
            title_kun: "Kun readings",
            title_on: "On readings",
            tooltip_stroke: "Stroke count",
            tooltip_grade: "Taught in this grade",
            tooltip_jlpt: "JLPT level",
            tooltip_frequency: "Newspaper frequency out of 2500",
            similar_kanji: "Similar:",
            reading_chinese: "Chinese reading:",
            reading_korean: "Korean reading:",
            reading_vietnamese: "Vietnamese reading:",
            anim_reset: "Reset",
        },
        names: {
            full_name: "Full name",
            sex: "Sex",
            origin: "Name origin",
        },
        sentences: {
            source_kevin: "Kevin Goes to Japan",
            source_tatoeba: "Tatoeba",
            three_dot: {
                sentence_search: "Sentence search",
                tatoeba_search: "Open in Tatoeba",
                direct_reference: "Direct reference",
            },
        },
        details: {
            common: {
                share: "Share",
            },
            tabs: {
                word: "Word",
                words: "Words",
                kanji: "Kanji",
                sentence: "Sentence",
                sentences: "Sentences",
                collocations: "Collocations",
                conjugations: "Conjugations",
                more: "More",
            },
            words: {
                conjugations: {
                    affirmative: "Affirmative",
                    negative: "Negative",
                    present: "Present",
                    present_polite: "Present (polite)",
                    past: "Past",
                    past_polite: "Past (polite)",
                    te_form: "Te form",
                    potential: "Potential",
                    passive: "Passive",
                    causative: "Causative",
                    causative_passive: "Causative passive",
                    imperative: "Imperative",
                },
                audio: {
                    tofugu: "Tofugu",
                    kanjialive: "Kanji alive",
                },
                switch: "Switch to {{pair}}",
                Transitive: "Transitive",
                Intransitive: "Intransitive",
                jlpt: "JLPT",
                frequency: "Frequency",
            },
        },
        bookmarks: {
            undo: "Undo",
            no_content:
                "<b>You don't have any bookmarks yet.</b><br/><br/> Search for a word, tap on it and you can find the feature in the top left corner!",
        },
        about: {
            title_about: "About us",
            content_about:
                "Jotoba is a multilingual Japanese dictionary. It is easy to find translations for words or kanji, see example sentences and the way names can be written. <br/><br/>" +
                "Check out our <trello>Trello Board</trello> if you are interested in upcoming features and what we are currently working on!",
            title_jotoKun: "Joto-kun",
            content_jotoKun: "Joto-kun was created by a good friend of ours who is truly a wizard when it comes down to design!",
            title_wkn: "Words & Kanji & Names",
            content_wkn:
                "Words, Kanji and Names available on this site are publicly provided and maintained by <edrdg>EDRDG</edrdg> " +
                "and available under the <ccsa>CC BY-SA 3.0.</ccsa> license.<br/><br/>" +
                "Additionally, the RADKFILE by Jin Breen is used to link Radicals to Kanji.",
            title_audio: "Audio Files",
            content_audio:
                "Audio files with the label 'Tofugu' were provided by <wanikani>Wanikani & Tofugu</wanikani> which can be found <audio>here</audio> and are licensed under <license>CC BY 4.0</license><br/><br/>" +
                "Audio files with the label 'Kanjialive' were provided by the <kanjialive>Kanji alive project</kanjialive> and have the same license.",
            title_sentences: "Sentences",
            content_sentences:
                "Sentences with the tag 'T' are provided by <tatoeba>Tatoeba</tatoeba> and are licensed under the Creative Commons CC 1.0 and 2.0 licenses<br/><br/>" +
                "Sentences with the tag 'K' are directly provided by the author of <kevin>Kevin Goes to Japan</kevin>",
            title_anim: "Kanji Animations",
            content_anim: "The raw data used for kanji animations is publicly provided by <anim>KanjiVG</anim>, a project by Ulrich Apel.",
            title_jlpt: "JLPT Data",
            content_jlpt: "Data about <jlpt>JLPT proficiencies</jlpt> are by provided by Jonathan Waller.",
            title_token: "Word tokenization",
            content_token:
                "<token>Word tokenization</token> is done using a project from Hideki Yamane and used for Japanese morphological analysis implementations.",
            title_pitch: "Pitch Accents",
            content_pitch: "Data about Pitch Accents are extracted from <unidic>UniDic</unidic>",
            title_furigana: "Furigana",
            content_furigana: "Furigana for words and names were provided by the <jmdictfurigana>JmdictFurigana</jmdictfurigana> project.",
        },
        info: {
            shortcuts: {
                title: "Shortcuts",
                description: "These shortcuts can be used anywhere when the input is not in focus.",
                shortcuts: {
                    global: {
                        title: "Global",
                        wsnk: "Change search category to words | sentences | names | kanji",
                        slash: "Focus the search bar",
                    },
                    words: {
                        title: "Words",
                        p: "Play the first audio on the page",
                    },
                },
            },
            searchbarShortcuts: {
                title: "Searchbar Shortcuts",
                description: "These shortcuts can be used anywhere when the input is in focus.",
                shortcuts: {
                    arrowsUpDown: "Iterate suggestions up | down",
                    tab: "Iterate a single suggestion down",
                    enter: "Search for the current suggestion if selected, search for query otherwise",
                },
            },
            radicalSearch: {
                title: "Radical Search",
                description: "Use Kanji, Kana or Romaji to search for radicals.",
                explanations: {
                    kanji: {
                        title: "Kanji",
                        description: "Results in all radicals used to build given kanji characters",
                    },
                    kana: {
                        title: "Kana",
                        description: "Searches in words for the given query and returns in result-matching radicals",
                    },
                    romaji: {
                        title: "Romaji",
                        description:
                            "Tries to find the given query in radicals names, otherwise does a word search and returns the result's kanji",
                    },
                },
            },
            hashtags: {
                title: "Hashtags",
                description: "Hashtags with a direct effect on the website.",
                headers: {
                    hashtag: "Hashtag",
                    description: "Description",
                    types: "Supported search types",
                },
                explanations: {
                    word: "Search in the [words] category",
                    sentence: "Search in the [sentences] category",
                    name: "Search in the [names] category",
                    kanji: "Search in the [kanji] category",
                    hidden: "Hide translations of results",
                },
                allTypes: "All types",
            },
            filterHashtags: {
                title: "Filter hashtags",
                description: "Filter the results of a search.",
            },
        },
    },
    paginator: {
        first: "First",
        last: "Last",
    },
    notifications: {
        title: "Notifications",
        no_notifications: "No new notifications",
        show: "Show all",
        close: "Close",
    },
    footer: {
        text: `Jotoba wouldn't be able to exist without the help of many open-source data sources.<br/>Check out the <a href="/about" aria-label="about us">About Page</a> for a list of all contributors in this project.`,
        trello: "Trello",
        discord: "Discord",
        instagram: "Instagram",
        donations: "PayPal <ex>donations will be shared between the developers!</ex>",
    },
    toast: {
        direct_reference_copied: "Direct reference copied to clipboard",
        furigana_copy: "Furigana copied to clipboard",
        url_copied: "URL copied to clipboard",
    },
    message_pages: {
        default_error: {
            message: "It looks like Joto is hard at work right now.",
            highlight: "Please try again later!",
        },
        no_result: {
            message: "We couldn't find what you were looking for.",
            message_alt: "We couldn't find what you were looking for but there are results in different categories:",
            highlight: "Try something different!",
        },
        no_internet: {
            message: "Disconnected",
            highlight: "Internet connection has been lost. <br/> Connect and try again!",
        },
        "404": {
            reason: "The page was not found",
            hint: "If you believe this is an error, create an issue on our GitHub page",
        },
        unknownCode: {
            reason: "An error occurred",
            hint: "If the error persists, create an issue on our GitHub page",
        },
        jotoba: {
            header: "Gotcha!",
            highlight: "We knew you'd be curious about our name!",
            message:
                '<jotoba>Jotoba</jotoba> is not a real word. It is derived from <kotoba /> where the "K" was replaced by a "J" which stands for "Japanese".',
        },
    },
};
