import { LanguageCode } from "@/JotoKit/ts/common";
import { Translation } from "@/JotoKit/ts/translations";

export const TRANSLATIONS_EN: Translation = {
    lang_value: LanguageCode.English,
    lang_names: {
        "en-US": "English",
        "de-DE": "German",
        "es-ES": "Spanish",
        "fr-FR": "French",
        "nl-NL": "Dutch",
        "sv-SE": "Swedish",
        ru: "Russian",
        hu: "Hungarian",
        "sl-SI": "Slovenian",
        "ja-JP": "Japanese",
    },
    searchbar: {
        placeholder: "Search...",
        rad_picker: {
            select_kanji: "Select Kanji",
            search_placeholder: "Search by Kanji...",
            select_kanji_placeholder: "Pick a radical to start searching for kanji",
        },
        image_overlay: {
            select: "Select an image",
            picture: "Take a picture",
            error: "Couldn't find any text!",
        },
        voice_overlay: {
            start: "click to start recording",
            stop: "click to stop recording",
            listening: "Speak now!",
            not_listening: "Waiting to start...",
            perm_denied: "Permission request failed! Please provide the microphone permission manually if needed.",
        },
        categories: {
            words: "Words",
            kanji: "Kanji",
            sentences: "Sentences",
            names: "Names",
        },
    },
    navbar: {
        title: {
            settings: "Settings",
            links: "Links",
        },
        action_button: {
            language: "Language",
            search: "Search",
            display: "Display",
            qol: "QoL",
            privacy: "Privacy",
            github: "Github",
            donation: "Donations",
            discord: "Discord",
            instagram: "Instagram",
            about: "About",
        },
        nav_button: {
            home: "Home",
            back: "Back",
            exit: "Exit",
        },
    },
    settings: {
        language: {
            title_language: "Language settings",
            title_langSelect: "Language settings",
            select_search: "Search language",
            select_page: "UI language",
            title_ordering: "Language ordering",
            checkbox_alwaysEnglish: "Always show English results",
            checkbox_englishOnTop: "Show English first",
        },
        search: {
            title_words: "Words",
            checkbox_showExampleSentences: "Show example sentences",
            checkbox_showKanjiBubbles: "Show kanji bubbles",
            checkbox_showKanjiTranslation: "Show kanji translation",
            title_sentences: "Sentences",
            checkbox_showFuri: "Show furigana",
            checkbox_hideTranslation: "Hide translation",
            title_kanji: "Kanji Page",
            show_other_langs: "Show other languages",
            show_kanji: "Show drawn Kanji on load",
            show_numbers: "Show Stroke number",
            anim_speed: "Animation Speed",
        },
        display: {
            title_theme: "Color Scheme",
            option_auto: "Automatic",
            option_dark: "Dark",
            option_light: "Light",
            title_itemsPerPage: "Page entries",
            words_per_page: "Words per Page",
            kanji_per_page: "Kanji per Page",
            names_per_page: "Names per Page",
            sentences_per_page: "Sentences per Page",
        },
        qol: {
            title_search: "Searchbar",
            checkbox_search_anim: "Enable input examples",
            checkbox_index_keyboard: "Close app along the index-keyboard",
            checkbox_focusAfterSearch: "Focus searchbar after search",
            checkbox_focusInputAfterSearch: "Select input after search",
            title_other: "Other",
            checkbox_use_japanese_fonts: "Use Jotoba's font choice",
            checkbox_enable_furi_copy: "Enable Furigana copy",
        },
        privacy: {
            title_privacy: "Privacy settings",
            allow_cookie: "Share usage statistics",
            explanation:
                "To help improve Jotoba, we collect certain anonymous data (in accordance with the GDPR) by default - but if you wish, we will stop collecting anything from you.",
        },
    },
    pages: {
        loader_messages: {
            0: "Counting words",
            1: "Drawing kanji",
            2: "Counting to infinity",
            3: "Planing new features",
            4: "Why don't you order a sandwich?",
            5: "Just count to 10",
            6: "Finding the Wifi cable",
            7: "Proving P=NP",
            8: "Adding randomly mispeled words",
            9: "TODO: Insert elevator music",
            10: "Our premium plan is faster",
            11: "Keeping all the 1's and removing all the 0's",
            12: "Help, I'm trapped in a loader!",
            13: "Adding non helpful loading messages",
            14: "Translating 「よろしく」",
        },
        index: {
            search: "Search",
            radicals: "Radicals",
        },
        words: {
            common: "common word",
            jlpt: "JLPT N",
            audio: {
                tofugu: "Tofugu",
                kanjialive: "Kanji alive",
            },
            number: "{{query}} is {{number}}",
            inflection: "We have detected the following inflection for {{query}} (<word>{{word}}</word>)",
            inflections: "We have detected the following inflections for {{query}} (<word>{{word}}</word>)",
            sentence_show: "Show example sentence",
            sentence_hide: "Hide example sentence",
            garaigo: "Wasei, {{language}} -> {{word}}",
            pitches: "Pitches",
            other_forms: "Other forms",
            three_dot: {
                show_collocations: "Show collocations",
                show_conjugations: "Show conjugations",
                suffix_transitivity: "Word",
                sentence_search: "Sentence search",
                download_audio_tofugu: "Tofugu audio",
                download_audio_kanjialive: "Kanjialive audio",
                edit: "Edit in JMDict",
                direct_reference: "Details",
            },
            xref: "See also <word/>",
            pos: {
                Noun: {
                    Normal: "Noun",
                    Adverbial: "Adv. noun",
                    Prefix: "Prefix",
                    Suffix: "Suffix",
                    Temporal: "Temporal noun",
                },
                Adjective: {
                    PreNounVerb: "Noun or verb describing a noun",
                    Keiyoushi: "I adj.",
                    KeiyoushiYoiIi: "I adj. (いい conjugated)",
                    Ku: "Ku adj.",
                    Na: "Na adj.",
                    Nari: "Na adj. (formal)",
                    No: "No adj.",
                    PreNoun: "Pre noun adj.",
                    Shiku: "Shiku adj.",
                    Taru: "Taru adj.",
                },
                Verb: {
                    Unspecified: "Unspecified verb",
                    Intransitive: "Intransitive",
                    Transitive: "Transitive",
                    Ichidan: "Ichidan",
                    IchidanZuru: "Ichidan (zuru)",
                    IchidanKureru: "Ichidan (kureru)",
                    Kuru: "Kuru verb",
                    Nidan: {
                        class: {
                            Upper: "Nidan verb (upper)",
                            Lower: "Nidan verb (lower)",
                        },
                    },
                    Yodan: {
                        Bu: "Yodanverb",
                        Dzu: "Yodan verb",
                        Gu: "Yodan verb",
                        Hu: "Yodan verb",
                        Ku: "Yodan verb",
                        Mu: "Yodan verb",
                        Nu: "Yodan verb",
                        Ru: "Yodan verb",
                        Su: "Yodan verb",
                        Tsu: "Yodan verb",
                        U: "Yodan verb",
                        Yu: "Yodan verb",
                        Zu: "Yodan verb",
                    },
                    Godan: {
                        Bu: "Godan verb",
                        Gu: "Godan verb",
                        Ku: "Godan verb",
                        Mu: "Godan erb",
                        Nu: "Godan verb",
                        Ru: "Godan verb",
                        Su: "Godan verb",
                        Tsu: "Godan verb",
                        U: "Godan verb",
                        Aru: "Godan verb",
                        USpecial: "Godan U verb (special)",
                        Uru: "Godan verb",
                        RuIrreg: "Godan verb",
                        IkuYuku: "Godan verb",
                    },
                    Irregular: {
                        Nu: "Irregular verb",
                        Ru: "Irregular verb",
                        Su: "Irregular verb",
                        NounOrAuxSuru: "Noun taking suru",
                        Suru: "Suru verb",
                        SuruSpecial: "Suru special",
                    },
                },
                Sfx: "SoundFx",
                Expr: "Expression",
                Counter: "Counter",
                Suffix: "Suffix",
                Prefix: "Prefix",
                Particle: "Particle",
                Interjection: "Interjection",
                Pronoun: "Pronoun",
                Numeric: "Numeric",
                Adverb: "Adverb",
                AdverbTo: "To-Adverb",
                Auxilary: "Auxiliary",
                AuxilaryAdj: "Auxiliary adjective",
                AuxilaryVerb: "Auxiliary verb",
                Conjunction: "Conjunction",
                Unclassified: "Unclassified",
            },
            word_class: {
                PreNoun: "Adnomen",
                Noun: "Noun",
                Pronoun: "Pronoun",
                Adjective: "Adjective",
                Verb: "Verb",
                Adverb: "Adverb",
                Particle: "Particle",
                Interjection: "Interjection",
                Symbol: "Symbol",
                Conjunction: "Conjunction",
                Suffix: "Suffix",
                Prefix: "Prefix",
                Space: "Space",
                Expr: "Expression",
            },
            field: {
                term: "term",
                Agriculture: "Agriculture",
                Anatomy: "Anatomy",
                Archeology: "Archeology",
                Architecture: "Architecture",
                ArtAesthetics: "Art aesthetics",
                Astronomy: "Astronomy",
                AudioVisual: "Audiovisual",
                Aviation: "Aviation",
                Baseball: "Baseball",
                Biochemistry: "Biochemistry",
                Biology: "Biology",
                Botany: "Botany",
                Buddhism: "Buddhism",
                Business: "Business",
                Chemistry: "Chemistry",
                Christianity: "Christianity",
                Computing: "Computing",
                Clothing: "Clothing",
                Crystallography: "Crystallography",
                Ecology: "Ecology",
                Economics: "Economics",
                Electricity: "Electricity",
                Electronics: "Electronics",
                Embryology: "Embryology",
                Engineering: "Engineering",
                Entomology: "Entomology",
                Finance: "Finance",
                Fishing: "Fishing",
                FoodCooking: "Food cooking",
                Gardening: "Gardening",
                Genetics: "Genetics",
                Geography: "Geography",
                Geology: "Geology",
                Geometry: "Geometry",
                GoGame: "Go (game)",
                Golf: "Golf",
                Grammar: "Grammar",
                GreekMythology: "Greek Mythology",
                Hanafuda: "Hanafuda",
                Horseracing: "Horseracing",
                Law: "Law",
                Linguistics: "Linguistics",
                Logic: "Logic",
                MartialArts: "Martial Arts",
                Mahjong: "Mahjong",
                Mathematics: "Mathematics",
                MechanicalEngineering: "Mechanical engineering",
                Medicine: "Medicine",
                ClimateWeather: "Climate / Weather",
                Military: "Military",
                Music: "Music",
                Ornithology: "Ornithology",
                Paleontology: "Paleontology",
                Pathology: "Pathology",
                Pharmacy: "Pharmacy",
                Philosophy: "Philosophy",
                Photography: "Photography",
                Physics: "Physics",
                Physiology: "Physiology",
                Printing: "Printing",
                Psychitatry: "Psychitatry",
                Shinto: "Shinto",
                Railway: "Railway",
                Shogi: "Shogi",
                Sports: "Sports",
                Statistics: "Statistics",
                Sumo: "Sumo",
                Telecommunications: "Telecommunications",
                Trademark: "Trademark",
                Videogame: "Videogame",
                Zoology: "Zoology",
                Cards: "Cards",
                Dentistry: "Dentistry",
                Kabuki: "Kabuki",
                Politics: "Politics",
                Psychology: "Psychology",
            },
            misc: {
                Abbreviation: "Abbreviation",
                Archaism: "Archaism",
                Character: "Character",
                ChildrensLanguage: "Childrens language",
                Colloquialism: "Colloquialism",
                CompanyName: "Company name",
                Creature: "Creature",
                DatedTerm: "Dated term",
                Deity: "Deity",
                Derogatory: "Derogatory",
                Document: "Document",
                Event: "Event",
                FamiliarLanguage: "Familiar language",
                FemaleTermOrLanguage: "Female term/language",
                Fiction: "Fiction",
                GivenName: "Given name",
                Group: "Group",
                HistoricalTerm: "Historical term",
                HonorificLanguage: "Honorific language",
                HumbleLanguage: "Humble language",
                IdiomaticExpression: "Idiomatic expression",
                JocularHumorousTerm: "Jocular humorous term",
                Legend: "Legend",
                LiteraryOrFormalTerm: "Literary/formal term",
                MangaSlang: "Manga slang",
                MaleTermOrLanguage: "Male term/language",
                Mythology: "Mythology",
                InternetSlang: "Internet slang",
                Object: "Object",
                ObsoleteTerm: "Obsolete term",
                ObscureTerm: "Obscure term",
                OnomatopoeicOrMimeticWord: "Onomatopoeic or mimetic word",
                OrganizationName: "Organization name",
                Other: "Other",
                Personname: "Person name",
                PlaceName: "Place name",
                PoeticalTerm: "Poetical term",
                PoliteLanguage: "Polite language",
                ProductName: "Product name",
                Proverb: "Proverb",
                Quotation: "Quotation",
                Rare: "Rare",
                Religion: "Religion",
                Sensitive: "Sensitive",
                Service: "Service",
                Slang: "Slang",
                RailwayStation: "Railway station",
                FamilyOrSurname: "Family or surname",
                UsuallyWrittenInKana: "Usually written in kana",
                UnclassifiedName: "Unclassified name",
                VulgarExpressionOrWord: "Vulgar expression/word",
                ArtWork: "Artwork",
                RudeOrXRatedTerm: "Rude/x-rated term",
                Yojijukugo: "Yojijukugo",
                Euphemistic: "Euphemistic",
            },
        },
        kanji: {
            strokes: "{{stroke_count}} strokes",
            jlpt: "JLPT N{{jlpt}}",
            grade: "Taught in {{grade}}. grade",
            radical: "Radical:",
            parts: "Parts:",
            kun: "Kun:",
            on: "On:",
            title_kun: "Kun readings",
            title_on: "On readings",
            tooltip_jouyou: "Jouyou kanji",
            tooltip_kokuji: "Kokuji kanji",
            tooltip_stroke: "Stroke count",
            tooltip_grade: "Taught in this grade",
            tooltip_jlpt: "JLPT level",
            tooltip_frequency: "Newspaper frequency out of 2500",
            similar_kanji: "Similar:",
            reading_chinese: "Chinese reading:",
            reading_korean: "Korean reading:",
            reading_vietnamese: "Vietnamese reading:",
            anim_reset: "Reset",
        },
        names: {
            full_name: "Full name",
            sex: "Sex",
            origin: "Name origin",
        },
        sentences: {
            source_kevin: "Kevin Goes to Japan",
            source_tatoeba: "Tatoeba",
            sentence_show: "[Show]",
            sentence_hide: "[Hide]",
            three_dot: {
                sentence_search: "Word search",
                tatoeba_search: "Open in Tatoeba",
                direct_reference: "Details",
            },
        },
        details: {
            common: {
                share: "Share",
            },
            tabs: {
                word: "Word",
                words: "Words",
                kanji: "Kanji",
                sentence: "Sentence",
                sentences: "Sentences",
                collocations: "Collocations",
                conjugations: "Conjugations",
                more: "More",
            },
            sentences: {
                source_kevin: "Kevin Goes to Japan",
                source_tatoeba: "Tatoeba",
            },
            words: {
                conjugations: {
                    affirmative: "Affirmative",
                    negative: "Negative",
                    present: "Present",
                    present_polite: "Present (polite)",
                    past: "Past",
                    past_polite: "Past (polite)",
                    te_form: "Te form",
                    potential: "Potential",
                    passive: "Passive",
                    causative: "Causative",
                    causative_passive: "Causative passive",
                    imperative: "Imperative",
                    ba: "Ba",
                    tara: "Tara",
                    zu: "Zu",
                },
                audio: {
                    tofugu: "Tofugu",
                    kanjialive: "Kanji alive",
                },
                switch: "Switch to {{pair}}",
                Transitive: "Transitive",
                Intransitive: "Intransitive",
                jlpt: "JLPT",
                frequency: "Frequency",
            },
        },
        bookmarks: {
            undo: "Undo",
            no_content:
                "<b>You don't have any bookmarks yet.</b><br/><br/> Search for a word, tap on it and you can find the feature in the top left corner!",
        },
        about: {
            title_about: "About us",
            content_about:
                "Jotoba is a multilingual Japanese dictionary built upon lots of free resources from the internet. It provides a lot of handy tools to lookup words, kanji, example sentences, Japanese names and much more. " +
                "On this page we want to say thank you to all those creating such wonderful resources that make something like Jotoba even possible.<br/><br/>" +
                "If you're interested in the development of Jotoba itself, check out our <trello>Trello Board</trello> and see what we are currently working on and what features will come in future releases!",
            dev_preview_frontend: "Frontend",
            dev_preview_backend: "Backend",
            title_jotoKun: "Joto-kun",
            content_jotoKun: "Joto-kun was created by a good friend of ours who is truly a wizard when it comes down to design!",
            title_wkn: "Words & Kanji & Names",
            content_wkn:
                "This site uses the <jmdict>JMdict</jmdict>, <kanjidic>KANJIDIC2</kanjidic>, <kradfile>KRADFILE</kradfile> and <jmnedict>JMnedict</jmnedict> dictionary files. " +
                "These files are the property of the <edrdg>Electronic Dictionary Research and Development Group</edrdg>, and are used in conformance with the Group's <license>licence</license>",
            title_audio: "Audio Files",
            content_audio:
                "Audio files with the label 'Tofugu' are provided by <tofugu>Tofugu's</tofugu> kanji and vocabulary learning site <wanikani>WaniKani</wanikani> and are licensed under <license>Creative Commons Attribution Share Alike 4.0</license>. " +
                "They can be found <audio>here</audio>.<br/><br/>" +
                "Audio files with the label 'Kanjialive' are provided by the <kanjialive>Kanji alive project</kanjialive> and are licensed under <kalicense>Creative Commons CC BY 4.0</kalicense> and can be found <kasource>here</kasource>.",
            title_sentences: "Sentences",
            content_sentences:
                "Example sentences with the tag 'T' come from <tatoeba>Tatoeba</tatoeba>, are licensed under <license>Creative Commons CC BY 2.0 FR</license> and are based on the Tanaka Corpus by Professor Yasuhito Tanaka. " +
                "Example sentences in word search also come from Tanaka corpus." +
                "<br/><br/>" +
                "Example Sentences with the tag 'K' are directly provided by the author of <kevin>Kevin Goes to Japan</kevin>.",
            title_anim: "Kanji stroke order",
            content_anim:
                "Information about kanji stroke order come from <anim>KanjiVG</anim>, which is copyright © 2009-2023 Ulrich Apel and licensed under <license>Creative Commons Attribution-Share Alike 3.0</license>." +
                "<br/><br/>" +
                "To convert this data into SVGs, we <altversion>alternated</altversion> and used the <kanjivgsvg>kanjivg2svg</kanjivgsvg> project by Kim Ahlström which is licensed under the <licenseKim>Creative Commons Attribution-Share Alike 3.0</licenseKim> license.",
            title_jlpt: "JLPT Data",
            content_jlpt:
                "Data about JLPT proficiencies are provided by <jw>Jonathan Waller's</jw> <jlpt>resources</jlpt> and licensed under <license>Creative Commons CC BY.</license>",
            title_furigana: "Furigana",
            content_furigana:
                "Furigana for words and names are provided by the <jmdictfurigana>JmdictFurigana</jmdictfurigana> project and are under the same license as JMdict (<license>Creative Commons Attribution-ShareAlike</license>).",
        },
        info: {
            shortcuts: {
                title: "Shortcuts",
                description: "These shortcuts can be used anywhere when the input is not in focus.",
                shortcuts: {
                    global: {
                        title: "Global",
                        wsnk: "Change search category to words | sentences | names | kanji",
                        slash: "Focus the search bar",
                    },
                    words: {
                        title: "Words",
                        p: "Play the first audio on the page",
                    },
                },
            },
            searchbarShortcuts: {
                title: "Searchbar Shortcuts",
                description: "These shortcuts can be used anywhere when the input is in focus.",
                shortcuts: {
                    arrowsUpDown: "Iterate suggestions up | down",
                    tab: "Iterate a single suggestion down",
                    enter: "Search for the current suggestion if selected, search for query otherwise",
                },
            },
            radicalSearch: {
                title: "Radical Search",
                description: "Use Kanji, Kana or Romaji to search for radicals.",
                explanations: {
                    kanji: {
                        title: "Kanji",
                        description: "Results in all radicals used to build given kanji characters",
                    },
                    kana: {
                        title: "Kana",
                        description: "Searches in words for the given query and returns in result-matching radicals",
                    },
                    romaji: {
                        title: "Romaji",
                        description:
                            "Tries to find the given query in radicals names, otherwise does a word search and returns the result's kanji",
                    },
                },
            },
            hashtags: {
                title: "Hashtags",
                description: "Hashtags with a direct effect on the website.",
                headers: {
                    hashtag: "Hashtag",
                    description: "Description",
                    types: "Supported search types",
                },
                explanations: {
                    word: "Search in the [words] category",
                    sentence: "Search in the [sentences] category",
                    name: "Search in the [names] category",
                    kanji: "Search in the [kanji] category",
                    hidden: "Hide translations of results",
                },
                allTypes: "All types",
            },
            filterHashtags: {
                title: "Filter hashtags",
                description: "Filter the results of a search.",
            },
        },
    },
    paginator: {
        first: "First",
        last: "Last",
    },
    notifications: {
        title: "Notifications",
        no_notifications: "No new notifications",
        show: "Show all",
        close: "Close",
    },
    footer: {
        socials: "Socials",
        trello: "Trello",
        discord: "Discord",
        instagram: "Instagram",
        support_us: "Support us",
        donations: "PayPal <ex>donations will be shared between the developers!</ex>",
        credits:
            "Jotoba uses a lot of free data sources. Some of the major ones are <jmdict>JMdict</jmdict>, <kanjidic>KANJIDIC2</kanjidic>, <kradfile>KRADFILE</kradfile> and <jmnedict>JMnedict</jmnedict> which are the property of the <edrdg>Electronic Dictionary Research and Development Group</edrdg>, and are used in conformance with the Group's <license>licence</license>.",
        credits_about: "Check out our <about>About Page</about> for a list of all contributors.",
        about: "About Page",
        privacy: "Privacy Policy",
    },
    toast: {
        direct_reference_copied: "Direct reference copied to clipboard",
        furigana_copied: "Furigana copied to clipboard",
        audio_copied: "Audio copied to clipboard",
        url_copied: "URL copied to clipboard",
    },
    message_pages: {
        default_error: {
            message: "It looks like Joto is hard at work right now.",
            highlight: "Please try again later!",
        },
        no_result: {
            message: "We couldn't find what you were looking for.",
            message_alt: "We couldn't find what you were looking for but there are results in different categories:",
            highlight: "Try something different!",
        },
        no_internet: {
            message: "Disconnected",
            highlight: "Internet connection has been lost. <br/> Connect and try again!",
        },
        "303": {
            reason: "See Other",
            hint: "If you believe this is an error, message us on discord!",
        },
        "400": {
            reason: "Bad Request",
            hint: "If you believe this is an error, message us on discord!",
        },
        "401": {
            reason: "Unauthorized",
            hint: "If you believe this is an error, message us on discord!",
        },
        "404": {
            reason: "The page was not found",
            hint: "If you believe this is an error, message us on discord!",
        },
        "408": {
            reason: "Request Timeout",
            hint: "If you believe this is an error, message us on discord!",
        },
        unknownCode: {
            reason: "An error occurred",
            hint: "If the error persists, message us on discord!",
        },
        jotoba: {
            header: "Gotcha!",
            highlight: "We knew you'd be curious about our name!",
            message:
                '<jotoba>Jotoba</jotoba> is not a real word. It is derived from <kotoba /> where the "K" was replaced by a "J" which stands for "Japanese".',
        },
    },
};
