import { LanguageCode } from "@/JotoKit/ts/common";
import { Translation } from "@/JotoKit/ts/translations";

export const TRANSLATIONS_JA: Translation = {
    lang_value: LanguageCode.German,
    lang_names: {
        "en-US": "英語",
        "de-DE": "ドイツ語",
        "es-ES": "スペイン語",
        "fr-FR": "フランス語",
        "nl-NL": "オランダ語",
        "sv-SE": "スウェーデン語",
        ru: "ロシア語",
        hu: "ハンガリー語",
        "sl-SI": "スロベニア語",
        "ja-JP": "日本語",
    },
    searchbar: {
        placeholder: "検索",
        rad_picker: {
            select_kanji: "漢字を選択",
            search_placeholder: "漢字を入力",
            select_kanji_placeholder: "部首を選択して漢字検索を開始",
        },
        image_overlay: {
            select: "画像を選択",
            picture: "新しい画像を作成",
            error: "テキストが見つかりませんでした。",
        },
        voice_overlay: {
            start: "タップして開始",
            stop: "タップして終了",
            listening: "音声入力待機中",
            not_listening: "開始シグナル待機中",
            perm_denied: "マイクの権限が取得できませんでした。必要な場合は、手動で許可してください。",
        },
        categories: {
            words: "単語",
            kanji: "漢字",
            sentences: "文",
            names: "名前",
        },
    },
    navbar: {
        title: {
            settings: "設定",
            links: "リンク",
        },
        action_button: {
            language: "言語",
            search: "検索",
            display: "表示",
            qol: "操作",
            privacy: "プライバシー",
            github: "Github",
            donation: "寄付",
            discord: "Discord",
            instagram: "Instagram",
            about: "Jotobaについて",
        },
        nav_button: {
            home: "ホーム",
            back: "戻る",
            exit: "アプリを終了",
        },
    },
    settings: {
        language: {
            title_language: "言語設定",
            title_langSelect: "言語選択",
            select_search: "検索に使用する言語",
            select_page: "アプリの言語",
            title_ordering: "表示順序",
            checkbox_alwaysEnglish: "常に英語の結果を表示",
            checkbox_englishOnTop: "英語の結果を先に表示",
        },
        search: {
            title_words: "単語",
            checkbox_showExampleSentences: "例文を表示",
            checkbox_showKanjiBubbles: "漢字を表示",
            checkbox_showKanjiTranslation: "漢字の意味を表示",
            title_sentences: "文",
            checkbox_showFuri: "ふりがなを表示",
            checkbox_hideTranslation: "翻訳を隠す",
            title_kanji: "漢字検索",
            anim_speed: "アニメーションの速度",
            show_other_langs: "他の言語を表示",
            show_kanji: "漢字アニメーションを描画済みの状態で表示する",
            show_numbers: "数字で順序を表示",
        },
        display: {
            title_theme: "テーマ",
            option_auto: "Automatic",
            option_dark: "Dark",
            option_light: "Light",
            title_itemsPerPage: "ページあたりの項目数",
            words_per_page: "ページあたりの単語数",
            kanji_per_page: "ページあたりの漢字数",
            names_per_page: "ページあたりの名前数",
            sentences_per_page: "ページあたりの文章数",
        },
        qol: {
            title_search: "検索バー",
            checkbox_search_anim: "入力例を表示",
            checkbox_index_keyboard: "キーボードを閉じてアプリを終了",
            checkbox_focusAfterSearch: "検索後も検索バーにカーソルを残す",
            checkbox_focusInputAfterSearch: "検索後に入力全体を選択",
            title_other: "その他",
            checkbox_use_japanese_fonts: "選択した日本語フォントを使用",
            checkbox_enable_furi_copy: "ふりがなコピーを有効にする",
        },
        privacy: {
            title_privacy: "プライバシー",
            allow_cookie: "ユーザーデータの取得を許可する",
            explanation:
                "Jotobaのサービス改善のため、ウェブサイトの利用に関するデータを取得しています。データは完全に匿名化されています。データの取得はいつでも停止できます。",
        },
    },
    pages: {
        loader_messages: {
            0: "単語を数える",
            1: "漢字を手書きする",
            2: "無限まで数を数える",
            3: "新しい機能を計画する",
            4: "ポップコーンを作る",
            5: "10まで数える",
            6: "Wi-Fiケーブルを探す",
            7: "P=NPを証明する",
            8: "ランダムなスペルミスを追加する",
            9: "Wi-Fiケーブルを挿し込む",
            10: "プレミアムにすると速くなる",
            11: "1はすべてそのまま、0はすべて削除する",
            12: "私をここから出してください",
            13: "読み込み中に表示するメッセージを他に考える",
            14: "「よろしく」を翻訳する",
        },
        index: {
            search: "検索",
            radicals: "部首",
        },
        words: {
            common: "一般的な単語",
            jlpt: "日本語能力試験 N",
            audio: {
                tofugu: "Tofugu",
                kanjialive: "Kanji alive",
            },
            number: "{{query}}は{{number}}です",
            inflection: "{{query}}は{{word}}の活用形の可能性があります。候補としては以下のものがあります。",
            inflections: "{{query}}は{{word}}の活用形の可能性があります。候補としては以下のものがあります。",
            sentence_show: "例文を表示",
            sentence_hide: "例文をたたむ",
            garaigo: "Wasei, {{language}} -> {{word}}",
            pitches: "ピッチアクセント",
            other_forms: "他の書き方・読み方",
            three_dot: {
                show_collocations: "コロケーションを表示",
                show_conjugations: "活用を表示",
                suffix_transitivity: "単語",
                sentence_search: "文を検索",
                download_audio_tofugu: "Tofuguの音声",
                download_audio_kanjialive: "Kanji aliveの音声",
                direct_reference: "詳細を見る",
            },
            xref: "See also <word>{{word}}</word>",
            pos: {
                Noun: {
                    Normal: "名詞",
                    Adverbial: "副詞的名詞",
                    Prefix: "接頭辞（名詞）",
                    Suffix: "接尾辞（名詞）",
                    Temporal: "時制に関する名詞",
                },
                Adjective: {
                    PreNounVerb: "名詞を説明する名詞または動詞",
                    Keiyoushi: "形容詞（〜い）",
                    KeiyoushiYoiIi: "形容詞（いいの活用形）",
                    Ku: "形容詞（〜く）",
                    Na: "形容詞（〜な）",
                    Nari: "文語的な形容詞（〜な）",
                    No: "の形容詞",
                    PreNoun: "名詞の前に置く形容詞",
                    Shiku: "形容詞（〜しく）",
                    Taru: "形容詞（〜たる）",
                },
                Verb: {
                    Unspecified: "未指定の動詞",
                    Intransitive: "自動詞",
                    Transitive: "他動詞",
                    Ichidan: "一段動詞",
                    IchidanZuru: "「ずる」を伴う一段動詞",
                    IchidanKureru: "「くれる」を伴う一段動詞",
                    Kuru: "「くる」動詞",
                    Nidan: {
                        class: {
                            Upper: "上二段活用",
                            Lower: "下二段活用",
                        },
                    },
                    Yodan: {
                        Bu: "四段活用 (〜ぶ)",
                        Dzu: "四段活用 (〜づ)",
                        Gu: "四段活用 (〜ぐ)",
                        Hu: "四段活用 (〜ふ)",
                        Ku: "四段活用 (〜く)",
                        Mu: "四段活用 (〜む)",
                        Nu: "四段活用 (〜ぬ)",
                        Ru: "四段活用 (〜る)",
                        Su: "四段活用 (〜す)",
                        Tsu: "四段活用 (〜つ)",
                        U: "四段活用 (〜う)",
                        Yu: "四段活用 (〜ゆ)",
                        Zu: "四段活用 (〜ず)",
                    },
                    Godan: {
                        Bu: "五段活用 (〜ぶ)",
                        Gu: "五段活用 (〜ぐ)",
                        Ku: "五段活用 (〜く)",
                        Mu: "五段活用 (〜む)",
                        Nu: "五段活用 (〜ぬ)",
                        Ru: "五段活用 (〜る)",
                        Su: "五段活用 (〜す)",
                        Tsu: "五段活用 (〜つ)",
                        U: "五段活用 (〜う)",
                        Aru: "「ある」動詞",
                        USpecial: "特殊な五段活用 (〜う)",
                        Uru: "五段活用 (〜うる)",
                        RuIrreg: "不規則な五段活用 (〜る)",
                        IkuYuku: "「いく」動詞",
                    },
                    Irregular: {
                        Nu: "「ぬ」で終わる不規則な動詞",
                        Ru: "「る」で終わる不規則な動詞",
                        Su: "「す」で終わる不規則な動詞",
                        NounOrAuxSuru: "名詞＋「する」",
                        Suru: "「する」動詞",
                        SuruSpecial: "特殊な「する」動詞",
                    },
                },
                Sfx: "効果音",
                Expr: "表現",
                Counter: "単位",
                Suffix: "接尾辞",
                Prefix: "接頭辞",
                Particle: "助詞",
                Interjection: "間投詞",
                Pronoun: "代名詞",
                Numeric: "数詞",
                Adverb: "副詞",
                AdverbTo: "副詞 (〜と)",
                Auxilary: "助動詞",
                AuxilaryAdj: "補助形容詞",
                AuxilaryVerb: "補助動詞",
                Conjunction: "接続詞",
                Unclassified: "未分類",
            },
            word_class: {
                PreNoun: "連体詞",
                Noun: "名詞",
                Pronoun: "代名詞",
                Adjective: "形容詞",
                Verb: "動詞",
                Adverb: "副詞",
                Particle: "助詞",
                Interjection: "間投詞",
                Symbol: "記号",
                Conjunction: "接続詞",
                Suffix: "接尾辞",
                Prefix: "接頭辞",
                Space: "スペース",
                Expr: "表現",
            },
            field: {
                term: "用語",
                Agriculture: "農業",
                Anatomy: "解剖学",
                Archeology: "考古学",
                Architecture: "建築学",
                ArtAesthetics: "芸術",
                Astronomy: "天文学",
                AudioVisual: "オーディオビジュアル (AV)",
                Aviation: "航空",
                Baseball: "野球",
                Biochemistry: "生化学",
                Biology: "生物学",
                Botany: "植物学",
                Buddhism: "仏教",
                Business: "ビジネス",
                Chemistry: "化学",
                Christianity: "キリスト教",
                Computing: "コンピューター",
                Clothing: "衣服",
                Crystallography: "結晶学",
                Ecology: "生態学",
                Economics: "経済学",
                Electricity: "電気",
                Electronics: "電子工学",
                Embryology: "発生学",
                Engineering: "工学",
                Entomology: "昆虫学",
                Finance: "財務",
                Fishing: "漁業",
                FoodCooking: "料理",
                Gardening: "園芸",
                Genetics: "遺伝学",
                Geography: "地理学",
                Geology: "地質学",
                Geometry: "幾何学",
                GoGame: "囲碁",
                Golf: "ゴルフ",
                Grammar: "文法",
                GreekMythology: "ギリシャ神話",
                Hanafuda: "花札",
                Horseracing: "競馬",
                Law: "法律",
                Linguistics: "言語学",
                Logic: "論理学",
                MartialArts: "格闘技",
                Mahjong: "麻雀",
                Mathematics: "数学",
                MechanicalEngineering: "機械工学",
                Medicine: "医学",
                ClimateWeather: "気候・天気",
                Military: "軍事",
                Music: "音楽",
                Ornithology: "鳥類学",
                Paleontology: "古生物学",
                Pathology: "病理学",
                Pharmacy: "薬学",
                Philosophy: "哲学",
                Photography: "写真",
                Physics: "物理学",
                Physiology: "生理学",
                Printing: "印刷",
                Psychitatry: "精神医学",
                Shinto: "神道",
                Railway: "鉄道",
                Shogi: "将棋",
                Sports: "スポーツ",
                Statistics: "統計学",
                Sumo: "相撲",
                Telecommunications: "通信",
                Trademark: "商標",
                Videogame: "ビデオゲーム",
                Zoology: "動物学",
                Cards: "トランプ",
                Dentistry: "歯学",
                Kabuki: "歌舞伎",
                Politics: "政治",
                Psychology: "心理学",
            },
            misc: {
                Abbreviation: "略語",
                Archaism: "古語",
                Character: "キャラクター",
                ChildrensLanguage: "幼児語",
                Colloquialism: "口語",
                CompanyName: "会社名",
                Creature: "生き物",
                DatedTerm: "古めかしい表現",
                Deity: "神",
                Derogatory: "ののしり言葉",
                Document: "文書",
                Event: "イベント",
                FamiliarLanguage: "親しみのこもった表現",
                FemaleTermOrLanguage: "女性語",
                Fiction: "フィクション",
                GivenName: "名前 (姓名の名)",
                Group: "グループ",
                HistoricalTerm: "歴史用語",
                HonorificLanguage: "敬語",
                HumbleLanguage: "謙譲語",
                IdiomaticExpression: "慣用表現",
                JocularHumorousTerm: "冗談めかした表現",
                Legend: "伝説",
                LiteraryOrFormalTerm: "文語",
                MangaSlang: "マンガのスラング",
                MaleTermOrLanguage: "男性語",
                Mythology: "神話",
                InternetSlang: "インターネットスラング",
                Object: "もの",
                ObsoleteTerm: "廃れた表現",
                ObscureTerm: "あいまいな表現",
                OnomatopoeicOrMimeticWord: "オノマトペ・擬態語・擬声語など",
                OrganizationName: "組織名",
                Other: "その他",
                Personname: "人名",
                PlaceName: "地名",
                PoeticalTerm: "詩的表現",
                PoliteLanguage: "丁寧語",
                ProductName: "製品名",
                Proverb: "ことわざ",
                Quotation: "引用",
                Rare: "使用頻度低",
                Religion: "宗教",
                Sensitive: "センシティブな表現",
                Service: "サービス",
                Slang: "俗語",
                RailwayStation: "鉄道駅",
                FamilyOrSurname: "苗字",
                UsuallyWrittenInKana: "通常ひらがなで書かれる",
                UnclassifiedName: "未分類の名前",
                VulgarExpressionOrWord: "下品な表現",
                ArtWork: "芸術作品",
                RudeOrXRatedTerm: "下品な表現・ポルノ表現",
                Yojijukugo: "四字熟語",
                Euphemistic: "婉曲表現",
            },
        },
        kanji: {
            strokes: "{{stroke_count}}画",
            jlpt: "日本語能力試験 N{{jlpt}}",
            grade: "{{grade}}年生で習う",
            radical: "部首：",
            parts: "構成部分：",
            kun: "訓読み：",
            on: "音読み：",
            title_kun: "訓読み",
            title_on: "音読み",
            tooltip_stroke: "画数",
            tooltip_grade: "習う学年",
            tooltip_jlpt: "日本語能力試験のレベル",
            tooltip_frequency: "新聞における出現頻度(2500語中)",
            similar_kanji: "似ている漢字：",
            reading_chinese: "中国語での読み方：",
            reading_korean: "韓国語での読み方：",
            reading_vietnamese: "ベトナム語での読み方：",
            anim_reset: "リセット",
        },
        names: {
            full_name: "フルネーム",
            sex: "性別",
            origin: "姓名",
        },
        sentences: {
            source_kevin: "Kevin Goes to Japan",
            source_tatoeba: "Tatoeba",
            sentence_show: "[Show]",
            sentence_hide: "[Hide]",
            three_dot: {
                sentence_search: "文を検索",
                tatoeba_search: "Open in Tatoeba",
                direct_reference: "詳細を見る",
            },
        },
        details: {
            common: {
                share: "共有する",
            },
            tabs: {
                word: "単語",
                words: "単語",
                kanji: "漢字",
                sentence: "文",
                sentences: "文",
                collocations: "コロケーション",
                conjugations: "活用形",
                more: "その他",
            },
            words: {
                conjugations: {
                    affirmative: "肯定形",
                    negative: "否定形",
                    present: "現在形",
                    present_polite: "現在形（丁寧）",
                    past: "過去形",
                    past_polite: "過去形（丁寧）",
                    te_form: "テ形",
                    potential: "可能形",
                    passive: "受身形",
                    causative: "使役形",
                    causative_passive: "使役受身形",
                    imperative: "命令形",
                },
                audio: {
                    tofugu: "Tofugu",
                    kanjialive: "Kanji alive",
                },
                switch: "{{pair}}に切り替える",
                Transitive: "他動詞",
                Intransitive: "自動詞",
                jlpt: "日本語能力試験レベル",
                frequency: "使用頻度",
            },
        },
        bookmarks: {
            undo: "ブックマークに戻す",
            no_content: "<b>まだブックマークがありません。</b><br/><br/>単語を検索してクリックし、上部左隅のアイコンから追加できます。",
        },
        about: {
            title_about: "Jotobaについて",
            content_about: "TODO",
            dev_preview_frontend: "Frontend",
            dev_preview_backend: "Backend",
            title_jotoKun: "Jotoくん",
            content_jotoKun: "Jotoくんのデザインは、管理人の友人が作成してくれました。",
            title_wkn: "単語／漢字／名前",
            content_wkn: "TODO",
            title_audio: "オーディオファイル",
            content_audio: "TODO",
            title_sentences: "例文",
            content_sentences: "TODO",
            title_anim: "漢字の書き順",
            content_anim: "TODO",
            title_jlpt: "日本語能力試験情報",
            content_jlpt: "TODO",
            title_token: "単語トークン化",
            content_token: "TODO",
            title_pitch: "トーンアクセント",
            content_pitch: "TODO",
            title_furigana: "ふりがな",
            content_furigana: "TODO",
        },
        info: {
            shortcuts: {
                title: "Shortcuts",
                description: "These shortcuts can be used anywhere when the input is not in focus.",
                shortcuts: {
                    global: {
                        title: "Global",
                        wsnk: "Change search category to words | sentences | names | kanji",
                        slash: "Focus the search bar",
                    },
                    words: {
                        title: "Words",
                        p: "Play the first audio on the page",
                    },
                },
            },
            searchbarShortcuts: {
                title: "Searchbar Shortcuts",
                description: "These shortcuts can be used anywhere when the input is in focus.",
                shortcuts: {
                    arrowsUpDown: "Iterate suggestions up | down",
                    tab: "Iterate a single suggestion down",
                    enter: "Search for the current suggestion if selected, search for query otherwise",
                },
            },
            radicalSearch: {
                title: "Radical Search",
                description: "Use Kanji, Kana or Romaji to search for radicals.",
                explanations: {
                    kanji: {
                        title: "Kanji",
                        description: "Results in all radicals used to build given kanji characters",
                    },
                    kana: {
                        title: "Kana",
                        description: "Searches in words for the given query and returns in result-matching radicals",
                    },
                    romaji: {
                        title: "Romaji",
                        description:
                            "Tries to find the given query in radicals names, otherwise does a word search and returns the result's kanji",
                    },
                },
            },
            hashtags: {
                title: "Hashtags",
                description: "Hashtags with a direct effect on the website.",
                headers: {
                    hashtag: "Hashtag",
                    description: "Description",
                    types: "Supported search types",
                },
                explanations: {
                    word: "Search in the [words] category",
                    sentence: "Search in the [sentences] category",
                    name: "Search in the [names] category",
                    kanji: "Search in the [kanji] category",
                    hidden: "Hide translations of results",
                },
                allTypes: "All types",
            },
            filterHashtags: {
                title: "Filter hashtags",
                description: "Filter the results of a search.",
            },
        },
    },
    paginator: {
        first: "First",
        last: "Last",
    },
    notifications: {
        title: "Notifications",
        no_notifications: "No new notifications",
        show: "Show all",
        close: "Close",
    },
    footer: {
        text: 'Jotobaは多くのオープンソースの支援なしでは存在できません。<br/>このプロジェクトに貢献してくださったすべての方々のリストは、<a href="/about" aria-label="about us">「Jotobaについて」</a>のページに掲載しています。',
        trello: "Trello",
        discord: "Discord",
        instagram: "Instagram",
        donations: "PayPal <ex>皆様からの寄付はすべての開発者間で分配されます。</ex>",
    },
    toast: {
        direct_reference_copied: "ダイレクトリンクがコピーされました",
        furigana_copied: "ふりがながコピーされました",
        audio_copied: "音声コピーされました",
        url_copied: "リンクがコピーされました",
    },
    message_pages: {
        default_error: {
            message: "Jotoくんは現在頑張っています。",
            highlight: "しばらくしてからもう一度お試しください。",
        },
        no_result: {
            message: "検索に一致する結果がありませんでした。",
            message_alt: "検索に一致する結果がありませんでした。こちらを試してみてください：",
            highlight: "別の検索ワードでお試しください。",
        },
        no_internet: {
            message: "接続が切断されました。",
            highlight: "インターネットに接続し、もう一度お試しください。",
        },
        "303": {
            reason: "See Other",
            hint: "If you believe this is an error, create an issue on our GitHub page",
        },
        "400": {
            reason: "Bad Request",
            hint: "If you believe this is an error, create an issue on our GitHub page",
        },
        "401": {
            reason: "Unauthorized",
            hint: "If you believe this is an error, create an issue on our GitHub page",
        },
        "404": {
            reason: "ページが見つかりませんでした。",
            hint: "問題が発生した場合は、GitHubでIssueを作成してください。",
        },
        "408": {
            reason: "Request Timeout",
            hint: "If you believe this is an error, create an issue on our GitHub page",
        },
        unknownCode: {
            reason: "An error occurred",
            hint: "If the error persists, create an issue on our GitHub page",
        },
        jotoba: {
            header: "Gotcha!",
            highlight: "We knew you'd be curious about our name!",
            message:
                '<jotoba>Jotoba</jotoba> is not a real word. It is derived from <kotoba /> where the "K" was replaced by a "J" which stands for "Japanese".',
        },
    },
};
