export const TRANSLATIONS_JA: Translation = {
    lang_value: "ja-JP",
    lang_names: {
        "en-US": "英語",
        "de-DE": "ドイツ語",
        "es-ES": "スペイン語",
        "fr-FR": "フランス語",
        "nl-NL": "オランダ語",
        "sv-SE": "スウェーデン語",
        ru: "ロシア語",
        hu: "ハンガリー語",
        "sl-SI": "スロベニア語",
        "ja-JP": "日本語",
    },
    searchbar: {
        placeholder: "検索",
        rad_picker: {
            select_kanji: "漢字を選択",
            search_placeholder: "漢字を入力",
            select_kanji_placeholder: "部首を選択して漢字検索を開始",
        },
        image_overlay: {
            select: "画像を選択",
            picture: "新しい画像を作成",
            error: "テキストが見つかりませんでした。",
        },
        voice_overlay: {
            start: "タップして開始",
            stop: "タップして終了",
            listening: "音声入力待機中",
            not_listening: "開始シグナル待機中",
            perm_denied: "マイクの権限が取得できませんでした。必要な場合は、手動で許可してください。",
        },
        categories: {
            words: "単語",
            kanji: "漢字",
            sentences: "文章",
            names: "名前",
        },
        ai_preview: {
            beta: "(beta)",
            message: "Try our new AI-powered search for better results:",
            enabled: "Enabled",
            disabled: "Disabled",
        },
    },
    navbar: {
        title: {
            profile: "プロフィール",
            settings: "設定",
            links: "リンク",
        },
        action_button: {
            language: "言語",
            search: "検索",
            display: "表示",
            qol: "操作",
            privacy: "プライバシー",
            github: "ギットハブ",
            donation: "寄付",
            discord: "Discord",
            instagram: "Instagram",
            about: "Jotobaについて",
            help: "Help",
            news: "News",
        },
        nav_button: {
            home: "ホーム",
            back: "戻る",
            exit: "アプリを終了",
        },
    },
    settings: {
        language: {
            title_language: "言語設定",
            title_langSelect: "言語選択",
            select_search: "検索に使用する言語",
            select_page: "アプリの言語",
            title_ordering: "表示順序",
            checkbox_alwaysEnglish: "常に英語の結果を表示",
            checkbox_englishOnTop: "英語の結果を先に表示",
        },
        search: {
            title_words: "単語",
            checkbox_showExampleSentences: "例文を表示",
            checkbox_showKanjiBubbles: "漢字を表示",
            checkbox_showKanjiTranslation: "漢字の意味を表示",
            title_sentences: "文章",
            checkbox_showFuri: "ふりがなを表示",
            checkbox_hideTranslation: "翻訳を隠す",
            title_kanji: "漢字検索",
            show_other_langs: "他の言語を表示",
            show_kanji: "漢字アニメーションを描画済みの状態で表示する",
            show_numbers: "数字で順序を表示",
            anim_speed: "アニメーションの速度",
        },
        display: {
            title_user_pref: "ユーザー設定",
            title_theme: "テーマ",
            option_auto: "自動",
            option_dark: "ダークモード",
            option_light: "ライトモード",
            title_jlpt: "日本語能力試験レベル",
            n5: "N5",
            n4: "N4",
            n3: "N3",
            n2: "N2",
            n1: "N1",
            title_itemsPerPage: "ページあたりの項目数",
            words_per_page: "ページあたりの単語数",
            kanji_per_page: "ページあたりの漢字数",
            names_per_page: "ページあたりの名前数",
            sentences_per_page: "ページあたりの文章数",
        },
        qol: {
            title_search: "検索バー",
            checkbox_search_anim: "入力例を表示",
            checkbox_index_keyboard: "キーボードを閉じてアプリを終了",
            checkbox_focusAfterSearch: "検索後も検索バーにカーソルを残す",
            checkbox_focusInputAfterSearch: "検索後に入力全体を選択",
            title_other: "その他",
            checkbox_use_japanese_fonts: "選択した日本語フォントを使用",
            checkbox_enable_furi_copy: "ふりがなコピーを有効にする",
        },
        privacy: {
            title_privacy: "プライバシー",
            allow_cookie: "ユーザーデータの取得を許可する",
            explanation:
                "Jotobaのサービス改善のため、ウェブサイトの利用に関するデータを取得しています。データは完全に匿名化されています。データの取得はいつでも停止できます。",
        },
    },
    pages: {
        loader_messages: {
            0: "単語を数える",
            1: "漢字を手書きする",
            2: "無限まで数を数える",
            3: "新しい機能を計画する",
            4: "ポップコーンを作る",
            5: "10まで数える",
            6: "Wi-Fiケーブルを探す",
            7: "P=NPを証明する",
            8: "ランダムなスペルミスを追加する",
            9: "Wi-Fiケーブルを挿し込む",
            10: "プレミアムにすると速くなる",
            11: "1はすべてそのまま、0はすべて削除する",
            12: "私をここから出してください",
            13: "読み込み中に表示するメッセージを他に考える",
            14: "「よろしく」を翻訳する",
        },
        index: {
            search: "検索",
            radicals: "部首",
            misc_links: {
                tour_text: "初めてですか?",
                tour_link: "使い方を簡単に見る",
            },
        },
        words: {
            common: "一般的な単語",
            jlpt: "日本語能力試験 N",
            audio: {
                tofugu: "Tofugu",
                kanjialive: "Kanji alive",
            },
            number: "{{query}}は{{number}}です",
            inflection: "<query />は<word />の活用形の可能性があります。候補としては以下のものがあります。",
            inflections: "<query />は<word />の活用形の可能性があります。候補としては以下のものがあります。",
            sentence_show: "例文を表示",
            sentence_hide: "例文をたたむ",
            garaigo: "和製, {{language}} -> {{word}}",
            pitches: "ピッチアクセント",
            other_forms: "他の書き方・読み方",
            three_dot: {
                show_collocations: "コロケーションを表示",
                show_conjugations: "活用を表示",
                suffix_transitivity: "単語",
                sentence_search: "例文を検索",
                download_audio_tofugu: "Tofuguの音声",
                download_audio_kanjialive: "Kanji aliveの音声",
                edit: "JMDictで編集する",
                direct_reference: "詳細を見る",
            },
            xref: "<word/>も見る",
            pos: {
                Noun: {
                    Normal: "名詞",
                    Adverbial: "副詞的名詞",
                    Prefix: "接頭辞（名詞）",
                    Suffix: "接尾辞（名詞）",
                    Temporal: "時制に関する名詞",
                },
                Adjective: {
                    PreNounVerb: "名詞を説明する名詞または動詞",
                    Keiyoushi: "形容詞",
                    KeiyoushiYoiIi: "形容詞（いいの活用形）",
                    Ku: "形容詞（〜く）",
                    Na: "ナ形容詞",
                    Nari: "文語的な形容詞（〜な）",
                    No: "の形容詞",
                    PreNoun: "名詞の前に置く形容詞",
                    Shiku: "形容詞（〜しく）",
                    Taru: "形容詞（〜たる）",
                },
                Verb: {
                    Unspecified: "未指定の動詞",
                    Intransitive: "自動詞",
                    Transitive: "他動詞",
                    Ichidan: "一段動詞",
                    IchidanZuru: "「ずる」を伴う一段動詞",
                    IchidanKureru: "「くれる」を伴う一段動詞",
                    Kuru: "「くる」動詞",
                    Nidan: {
                        class: {
                            Upper: "上二段活用",
                            Lower: "下二段活用",
                        },
                    },
                    Yodan: {
                        Bu: "四段活用 (〜ぶ)",
                        Dzu: "四段活用 (〜づ)",
                        Gu: "四段活用 (〜ぐ)",
                        Hu: "四段活用 (〜ふ)",
                        Ku: "四段活用 (〜く)",
                        Mu: "四段活用 (〜む)",
                        Nu: "四段活用 (〜ぬ)",
                        Ru: "四段活用 (〜る)",
                        Su: "四段活用 (〜す)",
                        Tsu: "四段活用 (〜つ)",
                        U: "四段活用 (〜う)",
                        Yu: "四段活用 (〜ゆ)",
                        Zu: "四段活用 (〜ず)",
                    },
                    Godan: {
                        Bu: "五段活用 (〜ぶ)",
                        Gu: "五段活用 (〜ぐ)",
                        Ku: "五段活用 (〜く)",
                        Mu: "五段活用 (〜む)",
                        Nu: "五段活用 (〜ぬ)",
                        Ru: "五段活用 (〜る)",
                        Su: "五段活用 (〜す)",
                        Tsu: "五段活用 (〜つ)",
                        U: "五段活用 (〜う)",
                        Aru: "「ある」動詞",
                        USpecial: "特殊な五段活用 (〜う)",
                        Uru: "五段活用 (〜うる)",
                        RuIrreg: "不規則な五段活用 (〜る)",
                        IkuYuku: "「いく」動詞",
                    },
                    Irregular: {
                        Nu: "「ぬ」で終わる不規則な動詞",
                        Ru: "「る」で終わる不規則な動詞",
                        Su: "「す」で終わる不規則な動詞",
                        NounOrAuxSuru: "名詞＋「する」",
                        Suru: "「する」動詞",
                        SuruSpecial: "特殊な「する」動詞",
                    },
                },
                Sfx: "効果音",
                Expr: "表現",
                Counter: "単位",
                Suffix: "接尾辞",
                Prefix: "接頭辞",
                Particle: "助詞",
                Interjection: "間投詞",
                Pronoun: "代名詞",
                Numeric: "数詞",
                Adverb: "副詞",
                AdverbTo: "副詞 (〜と)",
                Auxilary: "助動詞",
                AuxilaryAdj: "補助形容詞",
                AuxilaryVerb: "補助動詞",
                Conjunction: "接続詞",
                Unclassified: "未分類",
            },
            word_class: {
                PreNoun: "連体詞",
                Noun: "名詞",
                Pronoun: "代名詞",
                Adjective: "形容詞",
                Verb: "動詞",
                Adverb: "副詞",
                Particle: "助詞",
                Interjection: "間投詞",
                Symbol: "記号",
                Conjunction: "接続詞",
                Suffix: "接尾辞",
                Prefix: "接頭辞",
                Space: "スペース",
                Expr: "表現",
            },
            field: {
                term: "用語",
                Agriculture: "農業",
                Anatomy: "解剖学",
                Archeology: "考古学",
                Architecture: "建築学",
                ArtAesthetics: "芸術",
                Astronomy: "天文学",
                AudioVisual: "オーディオビジュアル (AV)",
                Aviation: "航空",
                Baseball: "野球",
                Biochemistry: "生化学",
                Biology: "生物学",
                Botany: "植物学",
                Buddhism: "仏教",
                Business: "ビジネス",
                Chemistry: "化学",
                Christianity: "キリスト教",
                Computing: "コンピューター",
                Clothing: "衣服",
                Crystallography: "結晶学",
                Ecology: "生態学",
                Economics: "経済学",
                Electricity: "電気",
                Electronics: "電子工学",
                Embryology: "発生学",
                Engineering: "工学",
                Entomology: "昆虫学",
                Finance: "財務",
                Fishing: "漁業",
                FoodCooking: "料理",
                Gardening: "園芸",
                Genetics: "遺伝学",
                Geography: "地理学",
                Geology: "地質学",
                Geometry: "幾何学",
                GoGame: "囲碁",
                Golf: "ゴルフ",
                Grammar: "文法",
                GreekMythology: "ギリシャ神話",
                Hanafuda: "花札",
                Horseracing: "競馬",
                Law: "法律",
                Linguistics: "言語学",
                Logic: "論理学",
                MartialArts: "格闘技",
                Mahjong: "麻雀",
                Mathematics: "数学",
                MechanicalEngineering: "機械工学",
                Medicine: "医学",
                ClimateWeather: "気候・天気",
                Military: "軍事",
                Music: "音楽",
                Ornithology: "鳥類学",
                Paleontology: "古生物学",
                Pathology: "病理学",
                Pharmacy: "薬学",
                Philosophy: "哲学",
                Photography: "写真",
                Physics: "物理学",
                Physiology: "生理学",
                Printing: "印刷",
                Psychitatry: "精神医学",
                Shinto: "神道",
                Railway: "鉄道",
                Shogi: "将棋",
                Sports: "スポーツ",
                Statistics: "統計学",
                Sumo: "相撲",
                Telecommunications: "通信",
                Trademark: "商標",
                Videogame: "ビデオゲーム",
                Zoology: "動物学",
                Cards: "トランプ",
                Dentistry: "歯学",
                Kabuki: "歌舞伎",
                Politics: "政治",
                Psychology: "心理学",
            },
            misc: {
                Abbreviation: "略語",
                Archaism: "古語",
                Character: "キャラクター",
                ChildrensLanguage: "幼児語",
                Colloquialism: "口語",
                CompanyName: "会社名",
                Creature: "生き物",
                DatedTerm: "古めかしい表現",
                Deity: "神",
                Derogatory: "ののしり言葉",
                Document: "文書",
                Event: "イベント",
                FamiliarLanguage: "親しみのこもった表現",
                FemaleTermOrLanguage: "女性語",
                Fiction: "フィクション",
                GivenName: "名前 (姓名の名)",
                Group: "グループ",
                HistoricalTerm: "歴史用語",
                HonorificLanguage: "敬語",
                HumbleLanguage: "謙譲語",
                IdiomaticExpression: "慣用表現",
                JocularHumorousTerm: "冗談めかした表現",
                Legend: "伝説",
                LiteraryOrFormalTerm: "文語",
                MangaSlang: "マンガのスラング",
                MaleTermOrLanguage: "男性語",
                Mythology: "神話",
                InternetSlang: "インターネットスラング",
                Object: "もの",
                ObsoleteTerm: "廃れた表現",
                ObscureTerm: "あいまいな表現",
                OnomatopoeicOrMimeticWord: "オノマトペ・擬態語・擬声語など",
                OrganizationName: "組織名",
                Other: "その他",
                Personname: "人名",
                PlaceName: "地名",
                PoeticalTerm: "詩的表現",
                PoliteLanguage: "丁寧語",
                ProductName: "製品名",
                Proverb: "ことわざ",
                Quotation: "引用",
                Rare: "使用頻度低",
                Religion: "宗教",
                Sensitive: "センシティブな表現",
                Service: "サービス",
                Slang: "俗語",
                RailwayStation: "鉄道駅",
                FamilyOrSurname: "苗字",
                UsuallyWrittenInKana: "通常ひらがなで書かれる",
                UnclassifiedName: "未分類の名前",
                VulgarExpressionOrWord: "下品な表現",
                ArtWork: "芸術作品",
                RudeOrXRatedTerm: "下品な表現・ポルノ表現",
                Yojijukugo: "四字熟語",
                Euphemistic: "婉曲表現",
            },
        },
        kanji: {
            strokes: "{{stroke_count}}画",
            jlpt: "日本語能力試験 N{{jlpt}}",
            grade: "{{grade}}年生で習う",
            radical: "部首：",
            parts: "構成部分：",
            kun: "訓読み：",
            on: "音読み：",
            title_kun: "訓読み",
            title_on: "音読み",
            tooltip_jouyou: "常用漢字",
            tooltip_kokuji: "和製漢字",
            tooltip_stroke: "画数",
            tooltip_grade: "習う学年",
            tooltip_jlpt: "日本語能力試験のレベル",
            tooltip_frequency: "新聞における出現頻度(2500語中)",
            similar_kanji: "似ている漢字：",
            reading_chinese: "中国語での読み方：",
            reading_korean: "韓国語での読み方：",
            reading_vietnamese: "ベトナム語での読み方：",
            anim_reset: "リセット",
        },
        names: {
            full_name: "フルネーム",
            sex: "性別",
            origin: "姓名",
        },
        sentences: {
            source_kevin: "Kevin Goes to Japan",
            source_tatoeba: "Tatoeba",
            sentence_show: "[表示]",
            sentence_hide: "[隠す]",
            three_dot: {
                sentence_search: "文を検索",
                tatoeba_search: "Tatoebaで開く",
                direct_reference: "詳細を見る",
            },
        },
        details: {
            common: {
                share: "共有する",
            },
            tabs: {
                word: "単語",
                words: "単語",
                kanji: "漢字",
                sentenceTl: "訳",
                sentences: "例文",
                collocations: "コロケーション",
                conjugations: "活用形",
                more: "その他",
            },
            sentences: {
                source_kevin: "Kevin Goes to Japan",
                source_tatoeba: "Tatoeba",
            },
            words: {
                conjugations: {
                    affirmative: "肯定形",
                    negative: "否定形",
                    present: "現在形",
                    present_polite: "現在形（丁寧）",
                    past: "過去形",
                    past_polite: "過去形（丁寧）",
                    te_form: "テ形",
                    potential: "可能形",
                    passive: "受身形",
                    causative: "使役形",
                    causative_passive: "使役受身形",
                    imperative: "命令形",
                    ba: "ば形",
                    tara: "たら形",
                    zu: "ず形",
                },
                audio: {
                    tofugu: "Tofugu",
                    kanjialive: "Kanji alive",
                },
                switch: "{{pair}}に切り替える",
                Transitive: "他動詞",
                Intransitive: "自動詞",
                jlpt: "日本語能力試験レベル",
                frequency: "使用頻度",
                edit: "JMDictで編集する",
            },
        },
        tour: {
            title_dropdown: "絞り込み検索",
            description_dropdown:
                "検索バー横の<g>下矢印</g>から<g>単語、漢字、文章、名前</g> を選択して検索できます。<br/><br/>また、 <g>キーボード</g> の <kbd>w</kbd> <kbd>k</kbd> <kbd>s</kbd> <kbd>n</kbd> を押して <g>検索対象</g> を <g>変更</g> することも可能です。",
            description_dropdown_mobile:
                "検索バー横の<g>上矢印</g>を押して、 <g>単語、漢字、文章、名前</g> から検索したいものを<g>選択します</g>。",
            title_multilang: "多言語",
            description_multilang: "<g>他の言語</g>の翻訳も表示したい場合は、<g>設定</g>で翻訳する<g>第二言語</g>を追加できます。",
            title_sentencereader: "文章解析ツール",
            description_sentencereader:
                "<g>日本語の文章全体</g>を検索し、抑揚のある<g>1つの単語</g>ごとに分解します。また、<g>ペンアイコン</g>を使って、<g>スペース</g>や<g>文字間</g>をクリックすることで、<g>分割された単語</g>を<g>カスタマイズ</g>することができます。",
            title_3dot: "3ドットメニュー",
            title_3dot_mobile: "詳細ページ",
            description_3dot:
                "検索結果の<g>3ドットメニュー</g>を選択すると、<g>直接そのリンク</g>や、<g>自動詞/他動詞</g>、<g>文章検索</g>など、<g>より多くの機能</g>にアクセスできます。",
            description_3dot_mobile: "検索結果の単語をクリックすると、自動詞/他動詞、使用漢字、例文などの詳細情報にアクセスできます。",
            title_kanjigraphs: "漢字構成要素",
            description_kanjigraphs:
                "漢字ページの漢字をクリックすると、その漢字の構成を見ることができます。右下のボタンで詳細表示とデフォルト表示が切り替わります。",
            action_next: "次へ",
            action_get_started: "始める",
            action_previous: "前へ",
        },
        bookmarks: {
            undo: "ブックマークに戻す",
            no_content: "<b>まだブックマークがありません。</b><br/><br/>単語を検索してクリックし、上部左隅のアイコンから追加できます。",
        },
        about: {
            title_about: "About us",
            content_about:
                "Jotoba is a multilingual Japanese dictionary built upon lots of free resources from the internet. It provides a lot of handy tools to lookup words, kanji, example sentences, Japanese names and much more. " +
                "On this page we want to say thank you to all those creating such wonderful resources that make something like Jotoba even possible.<br/><br/>" +
                "If you're interested in the development of Jotoba itself, check out our <trello>Trello Board</trello> and see what we are currently working on and what features will come in future releases!",
            dev_preview_frontend: "Frontend",
            dev_preview_backend: "Backend",
            title_jotoKun: "Joto-kun",
            content_jotoKun: "Joto-kun was created by a good friend of ours who is truly a wizard when it comes down to design!",
            title_wkn: "Words & Kanji & Names",
            content_wkn:
                "This site uses the <jmdict>JMdict</jmdict>, <kanjidic>KANJIDIC2</kanjidic>, <kradfile>KRADFILE</kradfile> and <jmnedict>JMnedict</jmnedict> dictionary files. " +
                "These files are the property of the <edrdg>Electronic Dictionary Research and Development Group</edrdg>, and are used in conformance with the Group's <license>licence</license>",
            title_audio: "Audio Files",
            content_audio:
                "Audio files with the label 'Tofugu' are provided by <tofugu>Tofugu's</tofugu> kanji and vocabulary learning site <wanikani>WaniKani</wanikani> and are licensed under <license>Creative Commons Attribution Share Alike 4.0</license>. " +
                "They can be found <audio>here</audio>.<br/><br/>" +
                "Audio files with the label 'Kanjialive' are provided by the <kanjialive>Kanji alive project</kanjialive> and are licensed under <kalicense>Creative Commons CC BY 4.0</kalicense> and can be found <kasource>here</kasource>.",
            title_sentences: "Sentences",
            content_sentences:
                "Example sentences with the tag 'T' come from <tatoeba>Tatoeba</tatoeba>, are licensed under <license>Creative Commons CC BY 2.0 FR</license> and are based on the Tanaka Corpus by Professor Yasuhito Tanaka. " +
                "Example sentences in word search also come from Tanaka corpus." +
                "<br/><br/>" +
                "Example Sentences with the tag 'K' are directly provided by the author of <kevin>Kevin Goes to Japan</kevin>.",
            title_anim: "Kanji stroke order",
            content_anim:
                "Information about kanji stroke order come from <anim>KanjiVG</anim>, which is copyright © 2009-2023 Ulrich Apel and licensed under <license>Creative Commons Attribution-Share Alike 3.0</license>." +
                "<br/><br/>" +
                "To convert this data into SVGs, we <altversion>alternated</altversion> and used the <kanjivgsvg>kanjivg2svg</kanjivgsvg> project by Kim Ahlström which is licensed under the <licenseKim>Creative Commons Attribution-Share Alike 3.0</licenseKim> license.",
            title_jlpt: "JLPT Data",
            content_jlpt:
                "Data about JLPT proficiencies are provided by <jw>Jonathan Waller's</jw> <jlpt>resources</jlpt> and licensed under <license>Creative Commons CC BY.</license>",
            title_furigana: "Furigana",
            content_furigana:
                "Furigana for words and names are provided by the <jmdictfurigana>JmdictFurigana</jmdictfurigana> project and are under the same license as JMdict (<license>Creative Commons Attribution-ShareAlike</license>).",
        },
        info: {
            tour: {
                title: "使い方",
                description: "-> Jotobaの重要な機能について<link>使い方を簡単に見る</link> ",
            },
            shortcuts: {
                title: "ショートカット",
                description: "これらのショートカットは、入力にフォーカスが当たっていないときならどこでも使えます",
                shortcuts: {
                    global: {
                        title: "サイト全体",
                        wsnk: "単語 | 文章 | 名前 | 漢字　の検索カテゴリーを変える",
                        slash: "検索バーにフォーカスする",
                    },
                    words: {
                        title: "単語ページ",
                        p: "ページ上の最初の単語を再生する",
                    },
                },
            },
            searchbarShortcuts: {
                title: "検索バーのショートカット",
                description: "これらのショートカットは、入力にフォーカスが当たっていればどこでも使えます",
                shortcuts: {
                    arrowsUpDown: "上 | 下　の検索予測",
                    tab: "1つ下の検索予測",
                    enter: "選択したものを検索する",
                },
            },
            radicalSearch: {
                title: "部首検索",
                description: "漢字、かな、ローマ字を使って検索できます",
                explanations: {
                    kanji: {
                        title: "漢字",
                        description: "入力した漢字を構成するすべての部首結果が見れます",
                    },
                    kana: {
                        title: "かな",
                        description: "単語で検索し、その漢字の部首を示します",
                    },
                    romaji: {
                        title: "ローマ字",
                        description: "部首名か単語で検索し、その漢字を示します",
                    },
                },
            },
            hashtags: {
                title: "ハッシュタグ",
                description: "ハッシュタグを使って直接検索できます",
                headers: {
                    hashtag: "ハッシュタグ",
                    description: "説明",
                    types: "対応する検索タイプ",
                },
                explanations: {
                    word: "「単語」カテゴリーを検索する",
                    sentence: "「文章」カテゴリーを検索する",
                    name: "「名前」カテゴリーを検索する",
                    kanji: "「漢字」カテゴリーを検索する",
                    hidden: "翻訳を隠す",
                },
                allTypes: "全て",
            },
            filterHashtags: {
                title: "ハッシュタグフィルター",
                description: "検索結果にフィルターをかける",
            },
        },
        imprint: {
            title: "Imprint",
            address: "Nils Reußwig<br />c/o IP-Management #41863 <br />Ludwig-Erhard-Str. 18 <br />20459 Hamburg <br />Germany",
            contact: "<b>Contact Information</b><br />Email: jotobadictionary@gmail.com",
            eu_law: '<b>EU Dispute Resolution</b><br />The European Commission provides a platform for online dispute resolution (ODR): <br /><a href="https://ec.europa.eu/consumers/odr/">ec.europa.eu/consumers/odr/</a>. <br />Our email address can be found above in the imprint.',
        },
    },
    paginator: {
        first: "最初",
        last: "最後",
    },
    login: {
        email: "Eメール",
        username: "ユーザーネーム",
        password: "パスワード",
        password_repeat: "リピートパスワード",
        login: "ログイン",
        register: "アカウント登録",
        logout: "ログアウト",
        not_registered: "まだアカウント登録されてませんか?",
        already_registered: "すでにアカウントをお持ちですか?",
        sign_in: "サインイン",
        create_account: "新しいアカウントを作る",
        login_success: "ログインしました",
        register_success: "アカウント登録が完了しました",
        logout_success: "ログアウトしました",
        error: {
            origin: {
                Email: "Email",
                Username: "Username",
            },
            simple: {
                default_toast: "An error occured. Please try again later!",
                invalid_login: "Invalid login credentials!",
                password_repeat: "Passwords do not match!",
            },
            constructed: {
                AlreadyExisting: "The {{type}} has already been used",
            },
        },
    },
    notifications: {
        title: "通知",
        show: "全て見る",
        close: "閉じる",
        none_available: "No news available",
    },
    footer: {
        socials: "SNS",
        trello: "Trello",
        discord: "Discord",
        instagram: "Instagram",
        reddit: "Reddit",
        support_us: "支援する",
        donations: "PayPal <ex>皆様からの寄付はすべての開発者間で分配されます。</ex>",
        credits_title: "About",
        credits:
            "Jotobaは多くのフリーデータソースを使用しています。主なものとして、<jmdict>JMdict</license>、<jmdict>KANJIDIC2</license>、<jmdict>KRADFILE</license>、<jmdict>JMnedict</license>がありますが、これらは<jmdict>the Electronic Dictionary Research and Development Group</license>のものであり、グループの<jmdict>ライセンス</license>に従って使用されています。",
        credits_about: " データソースについて<about>Jotobaについて</about> で見る",
        links_title: "Links",
        about: "Jotobaについて",
        applink: "携帯アプリ",
        privacy: "プライバシーポリシー",
        imprint: "Imprint",
    },
    toast: {
        direct_reference_copied: "ダイレクトリンクがコピーされました",
        furigana_copied: "ふりがながコピーされました",
        audio_copied: "音声コピーされました",
        url_copied: "リンクがコピーされました",
        error: {
            default: "An unknown error occured. Please try again later",
        },
        language_preview: {
            title: "Language preview",
            description: "You are currently seeing results in {{currentLang}}. Do you want to swap to {{userLang}}?",
            swap: "Swap to {{userLang}}",
            stay: "Stay on {{currentLang}}",
        },
    },
    message_pages: {
        default_error: {
            message: "Jotoくんは現在頑張っています。",
            highlight: "しばらくしてからもう一度お試しください。",
        },
        no_result: {
            message: "検索に一致する結果がありませんでした。",
            message_alt: "検索に一致する結果がありませんでした。こちらを試してみてください：",
            highlight: "別の検索ワードでお試しください。",
        },
        "303": {
            reason: "See Other",
            hint: "If you believe this is an error, message us on discord!",
        },
        "400": {
            reason: "Bad Request",
            hint: "If you believe this is an error, message us on discord!",
        },
        "401": {
            reason: "Unauthorized",
            hint: "If you believe this is an error, message us on discord!",
        },
        "404": {
            reason: "ページが見つかりませんでした。",
            hint: "もし間違いだと思われる場合は、Discordでお知らせください。",
        },
        "408": {
            reason: "Request Timeout",
            hint: "If you believe this is an error, message us on discord!",
        },
        unknownCode: {
            reason: "An error occurred",
            hint: "If the error persists, message us on discord!",
        },
        jotoba: {
            header: "わかってたよ!",
            highlight: "私たちの名前が気になるだろうっ思ってた！",
            message:
                "<jotoba>Jotoba</jotoba> は日本語の単語ではありません。 <kotoba /> の「K」が「Japanese」の「J」に置き換わったものです。",
        },
    },
    share: {
        title: "このページをシェアする",
    },
};
