export const TRANSLATIONS_PT: Translation = {
    lang_value: "pt",
    lang_names: {
        "en-US": "Inglês",
        "de-DE": "Alemão",
        "es-ES": "Espanhol",
        "fr-FR": "Francês",
        "nl-NL": "Holandês",
        "sv-SE": "Sueco",
        ru: "Russo",
        hu: "Húngaro",
        "sl-SI": "Esloveno",
        "ja-JP": "Japonês",
        pt: "Português",
    },
    searchbar: {
        placeholder: "Pesquisar...",
        rad_picker: {
            select_kanji: "Selecionar Kanji",
            search_placeholder: "Procurar por radicais...",
            select_kanji_placeholder:
                "Escolha um radical para começar a buscar kanji",
        },
        image_overlay: {
            select: "Selecionar uma imagem",
            picture: "Tirar uma foto",
            error: "Não foi possível encontrar nenhum texto!",
        },
        voice_overlay: {
            start: "clique para começar a gravação",
            stop: "clique para parar a gravação",
            listening: "Fale agora!",
            not_listening: "Aguardando para iniciar...",
            perm_denied:
                "Solicitação de permissão falhou! Por favor, forneça a permissão de microfone manualmente, se necessário.",
        },
        categories: {
            words: "Palavras",
            kanji: "Kanji",
            sentences: "Frases",
            names: "Nomes",
        },
        ai_preview: {
            beta: "(beta)",
            message:
                "Experimente nossa nova pesquisa com IA para melhores resultados:",
            enabled: "Ativado",
            disabled: "Desativado",
        },
    },
    navbar: {
        title: {
            profile: "Perfil",
            settings: "Configurações",
            links: "Links",
        },
        action_button: {
            language: "Idioma",
            search: "Pesquisa",
            display: "Exibição",
            qol: "QoL",
            privacy: "Privacidade",
            github: "Github",
            donation: "Doações",
            discord: "Discord",
            instagram: "Instagram",
            about: "Sobre",
            help: "Ajuda",
            news: "Notícias",
        },
        nav_button: {
            home: "Início",
            back: "Voltar",
            exit: "Sair",
        },
    },
    settings: {
        language: {
            title_language: "Configurações de idioma",
            title_langSelect: "Configurações de idioma",
            select_search: "Idioma de pesquisa",
            select_page: "Idioma da interface",
            title_ordering: "Ordenação de idiomas",
            checkbox_alwaysEnglish: "Sempre mostrar resultados em inglês",
            checkbox_englishOnTop: "Mostrar inglês primeiro",
        },
        search: {
            title_words: "Palavras",
            checkbox_showExampleSentences: "Mostrar frases de exemplo",
            checkbox_showKanjiBubbles: "Mostrar bolhas de kanji",
            checkbox_showKanjiTranslation: "Mostrar tradução de kanji",
            title_sentences: "Frases",
            checkbox_showFuri: "Mostrar furigana",
            checkbox_hideTranslation: "Ocultar tradução",
            title_kanji: "Página Kanji",
            show_other_langs: "Mostrar outros idiomas",
            show_kanji: "Mostrar Kanji desenhado ao carregar",
            show_numbers: "Mostrar número de traços",
            anim_speed: "Velocidade de animação",
        },
        display: {
            title_user_pref: "Preferência do usuário",
            title_theme: "Esquema de cores",
            option_auto: "Automático",
            option_dark: "Escuro",
            option_light: "Claro",
            title_jlpt: "Nível JLPT",
            n5: "N5",
            n4: "N4",
            n3: "N3",
            n2: "N2",
            n1: "N1",
            title_itemsPerPage: "Entradas por página",
            words_per_page: "Palavras por página",
            kanji_per_page: "Kanji por página",
            names_per_page: "Nomes por página",
            sentences_per_page: "Frases por página",
        },
        qol: {
            title_search: "Barra de pesquisa",
            checkbox_search_anim: "Ativar exemplos de entrada",
            checkbox_index_keyboard: "Fechar app junto com o teclado de índice",
            checkbox_focusAfterSearch: "Focar barra de pesquisa após busca",
            checkbox_focusInputAfterSearch: "Selecionar entrada após busca",
            title_other: "Outros",
            checkbox_use_japanese_fonts: "Usar escolha de fonte do Jotoba",
            checkbox_enable_furi_copy: "Ativar cópia de Furigana",
        },
        privacy: {
            title_privacy: "Configurações de privacidade",
            allow_cookie: "Compartilhar estatísticas de uso",
            explanation:
                "Para ajudar a melhorar o Jotoba, coletamos certos dados anônimos (de acordo com o GDPR) por padrão - mas se desejar, interromperemos a coleta de qualquer informação sua.",
        },
    },
    pages: {
        loader_messages: {
            0: "Contando palavras",
            1: "Desenhando kanji",
            2: "Contando até o infinito",
            3: "Planejando novos recursos",
            4: "Por que você não pede um sanduíche?",
            5: "Apenas conte até 10",
            6: "Encontrando o cabo do Wi-Fi",
            7: "Provando que P=NP",
            8: "Adicionando palavras aleatoriamente mal escritas",
            9: "TODO: Inserir música de elevador",
            10: "Nosso plano premium é mais rápido",
            11: "Mantendo todos os 1's e removendo todos os 0's",
            12: "Socorro, estou preso em um carregador!",
            13: "Adicionando mensagens de carregamento não úteis",
            14: "Traduzindo 「よろしく」",
        },
        index: {
            search: "Pesquisar",
            radicals: "Radicais",
            misc_links: {
                tour_text: "Novo por aqui? Comece",
                tour_link: "fazendo um tour rápido",
            },
        },
        words: {
            common: "palavra comum",
            jlpt: "JLPT N",
            audio: {
                tofugu: "Tofugu",
                kanjialive: "Kanji alive",
            },
            number: "{{query}} é {{number}}",
            inflection:
                "Detectamos a seguinte flexão para <query /> (<word />)",
            inflections:
                "Detectamos as seguintes flexões para <query /> (<word />)",
            sentence_show: "Mostrar frase de exemplo",
            sentence_hide: "Ocultar frase de exemplo",
            garaigo: "Wasei, {{language}} -> {{word}}",
            pitches: "Entonações",
            other_forms: "Outras formas",
            three_dot: {
                show_collocations: "Mostrar colocações",
                show_conjugations: "Mostrar conjugações",
                suffix_transitivity: "Palavra",
                sentence_search: "Pesquisa de frases",
                download_audio_tofugu: "Áudio Tofugu",
                download_audio_kanjialive: "Áudio Kanjialive",
                edit: "Editar no JMDict",
                direct_reference: "Detalhes",
            },
            xref: "Veja também <word/>",
            pos: {
                Noun: {
                    Normal: "Substantivo",
                    Adverbial: "Subst. adverbial",
                    Prefix: "Prefixo",
                    Suffix: "Sufixo",
                    Temporal: "Substantivo temporal",
                },
                Adjective: {
                    PreNounVerb:
                        "Substantivo ou verbo descrevendo um substantivo",
                    Keiyoushi: "Adj. I",
                    KeiyoushiYoiIi: "Adj. I (いい conjugado)",
                    Ku: "Adj. Ku",
                    Na: "Adj. Na",
                    Nari: "Adj. Na (formal)",
                    No: "Adj. No",
                    PreNoun: "Adj. pré-substantivo",
                    Shiku: "Adj. Shiku",
                    Taru: "Adj. Taru",
                },
                Verb: {
                    Unspecified: "Verbo não especificado",
                    Intransitive: "Intransitivo",
                    Transitive: "Transitivo",
                    Ichidan: "Ichidan",
                    IchidanZuru: "Ichidan (zuru)",
                    IchidanKureru: "Ichidan (kureru)",
                    Kuru: "Verbo Kuru",
                    Nidan: {
                        class: {
                            Upper: "Verbo Nidan (superior)",
                            Lower: "Verbo Nidan (inferior)",
                        },
                    },
                    Yodan: {
                        Bu: "Verbo Yodan",
                        Dzu: "Verbo Yodan",
                        Gu: "Verbo Yodan",
                        Hu: "Verbo Yodan",
                        Ku: "Verbo Yodan",
                        Mu: "Verbo Yodan",
                        Nu: "Verbo Yodan",
                        Ru: "Verbo Yodan",
                        Su: "Verbo Yodan",
                        Tsu: "Verbo Yodan",
                        U: "Verbo Yodan",
                        Yu: "Verbo Yodan",
                        Zu: "Verbo Yodan",
                    },
                    Godan: {
                        Bu: "Verbo Godan",
                        Gu: "Verbo Godan",
                        Ku: "Verbo Godan",
                        Mu: "Verbo Godan",
                        Nu: "Verbo Godan",
                        Ru: "Verbo Godan",
                        Su: "Verbo Godan",
                        Tsu: "Verbo Godan",
                        U: "Verbo Godan",
                        Aru: "Verbo Godan",
                        USpecial: "Verbo Godan U (especial)",
                        Uru: "Verbo Godan",
                        RuIrreg: "Verbo Godan",
                        IkuYuku: "Verbo Godan",
                    },
                    Irregular: {
                        Nu: "Verbo irregular",
                        Ru: "Verbo irregular",
                        Su: "Verbo irregular",
                        NounOrAuxSuru: "Substantivo com suru",
                        Suru: "Verbo Suru",
                        SuruSpecial: "Suru especial",
                    },
                },
                Sfx: "Efeito sonoro",
                Expr: "Expressão",
                Counter: "Contador",
                Suffix: "Sufixo",
                Prefix: "Prefixo",
                Particle: "Partícula",
                Interjection: "Interjeição",
                Pronoun: "Pronome",
                Numeric: "Numérico",
                Adverb: "Advérbio",
                AdverbTo: "Advérbio-To",
                Auxilary: "Auxiliar",
                AuxilaryAdj: "Adjetivo auxiliar",
                AuxilaryVerb: "Verbo auxiliar",
                Conjunction: "Conjunção",
                Unclassified: "Não classificado",
            },
            word_class: {
                PreNoun: "Adnome",
                Noun: "Substantivo",
                Pronoun: "Pronome",
                Adjective: "Adjetivo",
                Verb: "Verbo",
                Adverb: "Advérbio",
                Particle: "Partícula",
                Interjection: "Interjeição",
                Symbol: "Símbolo",
                Conjunction: "Conjunção",
                Suffix: "Sufixo",
                Prefix: "Prefixo",
                Space: "Espaço",
                Expr: "Expressão",
            },
            field: {
                term: "termo",
                Agriculture: "Agricultura",
                Anatomy: "Anatomia",
                Archeology: "Arqueologia",
                Architecture: "Arquitetura",
                ArtAesthetics: "Estética da arte",
                Astronomy: "Astronomia",
                AudioVisual: "Audiovisual",
                Aviation: "Aviação",
                Baseball: "Beisebol",
                Biochemistry: "Bioquímica",
                Biology: "Biologia",
                Botany: "Botânica",
                Buddhism: "Budismo",
                Business: "Negócios",
                Chemistry: "Química",
                Christianity: "Cristianismo",
                Computing: "Computação",
                Clothing: "Vestuário",
                Crystallography: "Cristalografia",
                Ecology: "Ecologia",
                Economics: "Economia",
                Electricity: "Eletricidade",
                Electronics: "Eletrônica",
                Embryology: "Embriologia",
                Engineering: "Engenharia",
                Entomology: "Entomologia",
                Finance: "Finanças",
                Fishing: "Pesca",
                FoodCooking: "Culinária",
                Gardening: "Jardinagem",
                Genetics: "Genética",
                Geography: "Geografia",
                Geology: "Geologia",
                Geometry: "Geometria",
                GoGame: "Go (jogo)",
                Golf: "Golfe",
                Grammar: "Gramática",
                GreekMythology: "Mitologia Grega",
                Hanafuda: "Hanafuda",
                Horseracing: "Corrida de cavalos",
                Law: "Direito",
                Linguistics: "Linguística",
                Logic: "Lógica",
                MartialArts: "Artes Marciais",
                Mahjong: "Mahjong",
                Mathematics: "Matemática",
                MechanicalEngineering: "Engenharia mecânica",
                Medicine: "Medicina",
                ClimateWeather: "Clima / Tempo",
                Military: "Militar",
                Music: "Música",
                Ornithology: "Ornitologia",
                Paleontology: "Paleontologia",
                Pathology: "Patologia",
                Pharmacy: "Farmácia",
                Philosophy: "Filosofia",
                Photography: "Fotografia",
                Physics: "Física",
                Physiology: "Fisiologia",
                Printing: "Impressão",
                Psychitatry: "Psiquiatria",
                Shinto: "Xintoísmo",
                Railway: "Ferrovia",
                Shogi: "Shogi",
                Sports: "Esportes",
                Statistics: "Estatística",
                Sumo: "Sumô",
                Telecommunications: "Telecomunicações",
                Trademark: "Marca registrada",
                Videogame: "Videogame",
                Zoology: "Zoologia",
                Cards: "Cartas",
                Dentistry: "Odontologia",
                Kabuki: "Kabuki",
                Politics: "Política",
                Psychology: "Psicologia",
            },
            misc: {
                Abbreviation: "Abreviação",
                Archaism: "Arcaísmo",
                Character: "Personagem",
                ChildrensLanguage: "Linguagem infantil",
                Colloquialism: "Coloquialismo",
                CompanyName: "Nome de empresa",
                Creature: "Criatura",
                DatedTerm: "Termo datado",
                Deity: "Divindade",
                Derogatory: "Depreciativo",
                Document: "Documento",
                Event: "Evento",
                FamiliarLanguage: "Linguagem familiar",
                FemaleTermOrLanguage: "Termo/linguagem feminino",
                Fiction: "Ficção",
                GivenName: "Nome próprio",
                Group: "Grupo",
                HistoricalTerm: "Termo histórico",
                HonorificLanguage: "Linguagem honorífica",
                HumbleLanguage: "Linguagem humilde",
                IdiomaticExpression: "Expressão idiomática",
                JocularHumorousTerm: "Termo jocoso/humorístico",
                Legend: "Lenda",
                LiteraryOrFormalTerm: "Termo literário/formal",
                MangaSlang: "Gíria de mangá",
                MaleTermOrLanguage: "Termo/linguagem masculino",
                Mythology: "Mitologia",
                InternetSlang: "Gíria da internet",
                Object: "Objeto",
                ObsoleteTerm: "Termo obsoleto",
                ObscureTerm: "Termo obscuro",
                OnomatopoeicOrMimeticWord: "Palavra onomatopeica ou mimética",
                OrganizationName: "Nome de organização",
                Other: "Outro",
                Personname: "Nome de pessoa",
                PlaceName: "Nome de lugar",
                PoeticalTerm: "Termo poético",
                PoliteLanguage: "Linguagem polida",
                ProductName: "Nome de produto",
                Proverb: "Provérbio",
                Quotation: "Citação",
                Rare: "Raro",
                Religion: "Religião",
                Sensitive: "Sensível",
                Service: "Serviço",
                Slang: "Gíria",
                RailwayStation: "Estação ferroviária",
                FamilyOrSurname: "Família ou sobrenome",
                UsuallyWrittenInKana: "Geralmente escrito em kana",
                UnclassifiedName: "Nome não classificado",
                VulgarExpressionOrWord: "Expressão/palavra vulgar",
                ArtWork: "Obra de arte",
                RudeOrXRatedTerm: "Termo rude/para adultos",
                Yojijukugo: "Yojijukugo",
                Euphemistic: "Eufemismo",
            },
        },
        kanji: {
            strokes: "{{stroke_count}} traços",
            jlpt: "JLPT N{{jlpt}}",
            grade: "Ensinado na {{grade}}a série",
            radical: "Radical:",
            parts: "Partes:",
            kun: "Kun:",
            on: "On:",
            title_kun: "Leituras Kun",
            title_on: "Leituras On",
            tooltip_jouyou: "Kanji Jouyou",
            tooltip_kokuji: "Kanji Kokuji",
            tooltip_stroke: "Contagem de traços",
            tooltip_grade: "Ensinado nesta série",
            tooltip_jlpt: "Nível JLPT",
            tooltip_frequency: "Frequência em jornais de 2500",
            similar_kanji: "Similares:",
            reading_chinese: "Leitura chinesa:",
            reading_korean: "Leitura coreana:",
            reading_vietnamese: "Leitura vietnamita:",
            anim_reset: "Reiniciar",
        },
        names: {
            full_name: "Nome completo",
            sex: "Sexo",
            origin: "Origem do nome",
        },
        sentences: {
            source_kevin: "Kevin Goes to Japan",
            source_tatoeba: "Tatoeba",
            sentence_show: "[Mostrar]",
            sentence_hide: "[Ocultar]",
            three_dot: {
                sentence_search: "Pesquisa de palavras",
                tatoeba_search: "Abrir no Tatoeba",
                direct_reference: "Detalhes",
            },
        },
        details: {
            common: {
                share: "Compartilhar",
            },
            tabs: {
                word: "Palavra",
                words: "Palavras",
                kanji: "Kanji",
                sentenceTl: "Tradução",
                sentences: "Frases",
                collocations: "Colocações",
                conjugations: "Conjugações",
                more: "Mais",
            },
            sentences: {
                source_kevin: "Kevin Goes to Japan",
                source_tatoeba: "Tatoeba",
            },
            words: {
                conjugations: {
                    affirmative: "Afirmativo",
                    negative: "Negativo",
                    present: "Presente",
                    present_polite: "Presente (polido)",
                    past: "Passado",
                    past_polite: "Passado (polido)",
                    te_form: "Forma te",
                    potential: "Potencial",
                    passive: "Passivo",
                    causative: "Causativo",
                    causative_passive: "Causativo passivo",
                    imperative: "Imperativo",
                    ba: "Ba",
                    tara: "Tara",
                    zu: "Zu",
                },
                audio: {
                    tofugu: "Tofugu",
                    kanjialive: "Kanji alive",
                },
                switch: "Mudar para {{pair}}",
                Transitive: "Transitivo",
                Intransitive: "Intransitivo",
                jlpt: "JLPT",
                frequency: "Frequência",
                edit: "Editar no JMDict",
            },
        },
        tour: {
            title_dropdown: "Pesquisa Avançada",
            description_dropdown:
                "Pesquise por <g>Palavras, Kanji, Frases</g> ou <g>Nomes</g> selecionando o <g>menu suspenso</g> ao lado da barra de pesquisa.<br/><br/>Você também pode <g>alternar</g> entre <g>alvos de pesquisa</g> pressionando <kbd>w</kbd> <kbd>k</kbd> <kbd>s</kbd> ou <kbd>n</kbd> no seu <g>teclado</g>.",
            description_dropdown_mobile:
                "Pesquise por <g>Palavras, Kanji, Frases</g> ou <g>Nomes</g> tocando na <g>seta para cima</g> na barra de pesquisa e <g>escolhendo</g> seu <g>alvo de pesquisa</g> desejado.",
            title_multilang: "Multi idioma",
            description_multilang:
                "Você pode adicionar um <g>segundo idioma de tradução</g> nas <g>configurações</g>.",
            title_sentencereader: "Leitor de frases",
            description_sentencereader:
                "Pesquise por uma <g>frase japonesa completa</g> para dividi-la em <g>palavras individuais</g> com <g>flexões</g>.<br/><br/>Usar o <g>ícone de caneta</g> permite <g>personalizar</g> a <g>divisão de palavras</g> clicando nos <g>espaços</g> ou <g>entre caracteres</g>.",
            title_3dot: "Menu de 3 pontos",
            title_3dot_mobile: "Página de detalhes",
            description_3dot:
                "Selecione o <g>menu de 3 pontos</g> em um resultado de pesquisa para acessar <g>mais recursos</g> como seu <g>link direto</g>, versão <g>in/transitiva</g>, <g>pesquisa de frases</g> e muito mais.",
            description_3dot_mobile:
                "<g>Clique</g> em uma Palavra no resultado da pesquisa para acessar <g>mais informações</g> como sua versão <g>in/transitiva</g>, <g>kanji</g> usados, <g>frases de exemplo</g> e muito mais.",
            title_kanjigraphs: "Gráfico de decomposição de Kanji",
            description_kanjigraphs:
                "Clique no <g>literal</g> de um kanji na <g>página de kanji</g> para ver como ele é feito.<br/><br/>Usar o <g>botão</g> no <g>canto inferior direito</g> alterna entre visualização <g>detalhada</g> e <g>padrão</g>.",
            action_next: "Próximo",
            action_get_started: "Começar",
            action_previous: "Anterior",
        },
        bookmarks: {
            undo: "Desfazer",
            no_content:
                "<b>Você ainda não tem favoritos.</b><br/><br/> Procure uma palavra, toque nela e você encontrará o recurso no canto superior esquerdo!",
        },
        about: {
            title_about: "Sobre nós",
            content_about:
                "Jotoba é um dicionário japonês multilíngue construído sobre muitos recursos gratuitos da internet. Ele fornece muitas ferramentas úteis para pesquisar palavras, kanji, frases de exemplo, nomes japoneses e muito mais. " +
                "Nesta página, queremos agradecer a todos aqueles que criam recursos tão maravilhosos que tornam algo como o Jotoba possível.<br/><br/>" +
                "Se você estiver interessado no desenvolvimento do Jotoba, confira nosso <trello>Quadro Trello</trello> e veja no que estamos trabalhando atualmente e quais recursos virão em versões futuras!",
            dev_preview_frontend: "Frontend",
            dev_preview_backend: "Backend",
            title_jotoKun: "Joto-kun",
            content_jotoKun:
                "Joto-kun foi criado por um bom amigo nosso que é verdadeiramente um mago quando se trata de design!",
            title_wkn: "Palavras & Kanji & Nomes",
            content_wkn:
                "Este site usa os arquivos de dicionário <jmdict>JMdict</jmdict>, <kanjidic>KANJIDIC2</kanjidic>, <kradfile>KRADFILE</kradfile> e <jmnedict>JMnedict</jmnedict>. " +
                "Esses arquivos são propriedade do <edrdg>Grupo de Pesquisa e Desenvolvimento de Dicionários Eletrônicos</edrdg>, e são usados em conformidade com a <license>licença</license> do Grupo",
            title_audio: "Arquivos de Áudio",
            content_audio:
                "Arquivos de áudio com o rótulo 'Tofugu' são fornecidos pelo site de aprendizado de kanji e vocabulário <tofugu>Tofugu's</tofugu> <wanikani>WaniKani</wanikani> e são licenciados sob <license>Creative Commons Attribution Share Alike 4.0</license>. " +
                "Eles podem ser encontrados <audio>aqui</audio>.<br/><br/>" +
                "Arquivos de áudio com o rótulo 'Kanjialive' são fornecidos pelo <kanjialive>projeto Kanji alive</kanjialive> e são licenciados sob <kalicense>Creative Commons CC BY 4.0</kalicense> e podem ser encontrados <kasource>aqui</kasource>.",
            title_sentences: "Frases",
            content_sentences:
                "Frases de exemplo com a tag 'T' vêm do <tatoeba>Tatoeba</tatoeba>, são licenciadas sob <license>Creative Commons CC BY 2.0 FR</license> e são baseadas no Corpus Tanaka do Professor Yasuhito Tanaka. " +
                "Frases de exemplo na pesquisa de palavras também vêm do corpus Tanaka." +
                "<br/><br/>" +
                "Frases de exemplo com a tag 'K' são fornecidas diretamente pelo autor de <kevin>Kevin Goes to Japan</kevin>.",
            title_anim: "Ordem dos traços Kanji",
            content_anim:
                "Informações sobre a ordem dos traços de kanji vêm do <anim>KanjiVG</anim>, que é copyright © 2009-2023 Ulrich Apel e licenciado sob <license>Creative Commons Attribution-Share Alike 3.0</license>." +
                "<br/><br/>" +
                "Para converter esses dados em SVGs, nós <altversion>alteramos</altversion> e usamos o projeto <kanjivgsvg>kanjivg2svg</kanjivgsvg> de Kim Ahlström, que é licenciado sob a licença <licenseKim>Creative Commons Attribution-Share Alike 3.0</licenseKim>.",
            title_jlpt: "Dados JLPT",
            content_jlpt:
                "Dados sobre proficiências JLPT são fornecidos por <jw>Jonathan Waller's</jw> <jlpt>recursos</jlpt> e licenciados sob <license>Creative Commons CC BY.</license>",
            title_furigana: "Furigana",
            content_furigana:
                "Furigana para palavras e nomes são fornecidos pelo projeto <jmdictfurigana>JmdictFurigana</jmdictfurigana> e estão sob a mesma licença que o JMdict (<license>Creative Commons Attribution-ShareAlike</license>).",
        },
        info: {
            tour: {
                title: "Tour",
                description:
                    "-> <link>Faça um tour rápido</link> para conhecer os recursos mais relevantes do Jotoba",
            },
            shortcuts: {
                title: "Atalhos",
                description:
                    "Estes atalhos podem ser usados em qualquer lugar.",
                shortcuts: {
                    global: {
                        title: "Global",
                        wsnk: "Mudar categoria de pesquisa para palavras | frases | nomes | kanji",
                        slash: "Focar na barra de pesquisa",
                    },
                    words: {
                        title: "Palavras",
                        p: "Reproduzir o primeiro áudio na página",
                    },
                },
            },
            searchbarShortcuts: {
                title: "Atalhos da Barra de Pesquisa",
                description:
                    "Estes atalhos podem ser usados em qualquer lugar quando o campo está em foco.",
                shortcuts: {
                    closeSuggestions: "Fechar sugestões",
                    openSuggestions: "Abrir sugestões",
                    arrowsUpDown: "Navegar sugestões para cima | baixo",
                    tab: "Navegar para a próxima sugestão",
                    enter: "Pesquisar a sugestão selecionada, ou pesquisar a consulta se nenhuma estiver selecionada",
                },
            },
            searchWildcards: {
                title: "Curingas de Pesquisa",
                warning: "[Apenas palavras]",
                description:
                    "Use curingas para melhorar seus resultados de pesquisa.",
                wildcards: {
                    single: "Curinga de caractere único",
                    multi: "Curinga de múltiplos caracteres",
                },
            },
            radicalSearch: {
                title: "Pesquisa por Radicais",
                description:
                    "Use Kanji, Kana ou Romaji para pesquisar radicais.",
                explanations: {
                    kanji: {
                        title: "Kanji",
                        description:
                            "Resulta em todos os radicais utilizados para construir os caracteres kanji fornecidos",
                    },
                    kana: {
                        title: "Kana",
                        description:
                            "Pesquisa nas palavras a consulta fornecida e retorna os radicais correspondentes aos resultados",
                    },
                    romaji: {
                        title: "Romaji",
                        description:
                            "Tenta encontrar a consulta fornecida nos nomes dos radicais, caso contrário faz uma pesquisa de palavras e retorna os kanji do resultado",
                    },
                },
            },
            hashtags: {
                title: "Hashtags",
                description: "Hashtags com efeito direto no site.",
                headers: {
                    hashtag: "Hashtag",
                    description: "Descrição",
                    types: "Tipos de pesquisa suportados",
                },
                explanations: {
                    word: "Pesquisar na categoria [palavras]",
                    sentence: "Pesquisar na categoria [frases]",
                    name: "Pesquisar na categoria [nomes]",
                    kanji: "Pesquisar na categoria [kanji]",
                    hidden: "Ocultar traduções dos resultados",
                },
                allTypes: "Todos os tipos",
            },
            filterHashtags: {
                title: "Hashtags de filtro",
                description: "Filtrar os resultados de uma pesquisa.",
            },
        },
        imprint: {
            title: "Impressão",
            address:
                "Nils Reußwig<br />c/o IP-Management #41863 <br />Ludwig-Erhard-Str. 18 <br />20459 Hamburgo <br />Alemanha",
            contact:
                "<b>Informações de Contato</b><br />Email: jotobadictionary@gmail.com",
            eu_law: '<b>Resolução de Disputas da UE</b><br />A Comissão Europeia fornece uma plataforma para resolução de disputas online (ODR): <br /><a href="https://ec.europa.eu/consumers/odr/">ec.europa.eu/consumers/odr/</a>. <br />Nosso endereço de email pode ser encontrado acima na impressão.',
        },
    },
    paginator: {
        first: "Primeiro",
        last: "Último",
    },
    login: {
        email: "Email",
        username: "Nome de usuário",
        password: "Senha",
        password_repeat: "Repetir senha",
        login: "Entrar",
        register: "Registrar",
        logout: "Sair",
        not_registered: "Não registrado?",
        already_registered: "Já registrado?",
        sign_in: "Entrar",
        create_account: "Criar uma nova conta",
        login_success: "Login bem-sucedido",
        register_success: "Registro bem-sucedido",
        logout_success: "Saiu com sucesso!",
        error: {
            origin: {
                Email: "Email",
                Username: "Nome de usuário",
            },
            simple: {
                default_toast:
                    "Ocorreu um erro. Por favor, tente novamente mais tarde!",
                invalid_login: "Credenciais de login inválidas!",
                password_repeat: "As senhas não coincidem!",
            },
            constructed: {
                AlreadyExisting: "O {{type}} já foi utilizado",
            },
        },
    },
    notifications: {
        title: "Notificações",
        show: "Mostrar todas",
        close: "Fechar",
        none_available: "Nenhuma notícia disponível",
    },
    footer: {
        socials: "Redes sociais",
        trello: "Trello",
        discord: "Discord",
        instagram: "Instagram",
        reddit: "Reddit",
        support_us: "Apoie-nos",
        donations:
            "Doações via PayPal <ex>serão compartilhadas entre os desenvolvedores!</ex>",
        credits_title: "Sobre",
        credits:
            "Jotoba usa muitas fontes de dados gratuitas. Algumas das principais são <jmdict>JMdict</jmdict>, <kanjidic>KANJIDIC2</kanjidic>, <kradfile>KRADFILE</kradfile> e <jmnedict>JMnedict</jmnedict>, que são propriedade do <edrdg>Grupo de Pesquisa e Desenvolvimento de Dicionários Eletrônicos</edrdg>, e são usadas em conformidade com a <license>licença</license> do Grupo.",
        credits_about:
            "Confira nossa <about>Página Sobre</about> para uma lista de todos os colaboradores.",
        links_title: "Links",
        about: "Página Sobre",
        applink: "Aplicativo Android",
        privacy: "Política de Privacidade",
        imprint: "Impressão",
    },
    toast: {
        direct_reference_copied:
            "Referência direta copiada para a área de transferência",
        furigana_copied: "Furigana copiado para a área de transferência",
        audio_copied: "Áudio copiado para a área de transferência",
        url_copied: "URL copiada para a área de transferência",
        error: {
            default:
                "Ocorreu um erro desconhecido. Por favor, tente novamente mais tarde",
        },
        language_preview: {
            title: "Pré-visualização de idioma",
            description:
                "Você está vendo resultados em {{currentLang}}. Deseja mudar para {{userLang}}?",
            swap: "Mudar para {{userLang}}",
            stay: "Permanecer em {{currentLang}}",
        },
    },
    message_pages: {
        default_error: {
            message: "Parece que o Joto está trabalhando arduamente agora.",
            highlight: "Por favor, tente novamente mais tarde!",
        },
        no_result: {
            message: "Não conseguimos encontrar o que você está procurando.",
            message_alt:
                "Não conseguimos encontrar o que você está procurando, mas há resultados em diferentes categorias:",
            highlight: "Tente algo diferente!",
        },
        "303": {
            reason: "Ver Outro",
            hint: "Se você acredita que isso é um erro, envie uma mensagem para nós no Discord!",
        },
        "400": {
            reason: "Requisição Inválida",
            hint: "Se você acredita que isso é um erro, envie uma mensagem para nós no Discord!",
        },
        "401": {
            reason: "Não Autorizado",
            hint: "Se você acredita que isso é um erro, envie uma mensagem para nós no Discord!",
        },
        "404": {
            reason: "Página não encontrada",
            hint: "Se você acredita que isso é um erro, envie uma mensagem para nós no Discord!",
        },
        "408": {
            reason: "Tempo Limite da Requisição",
            hint: "Se você acredita que isso é um erro, envie uma mensagem para nós no Discord!",
        },
        unknownCode: {
            reason: "Ocorreu um erro",
            hint: "Se o erro persistir, envie uma mensagem para nós no Discord!",
        },
        jotoba: {
            header: "Pegamos você!",
            highlight: "Sabíamos que você ficaria curioso sobre nosso nome!",
            message:
                '<jotoba>Jotoba</jotoba> não é uma palavra real. É derivada de <kotoba /> onde o "K" foi substituído por um "J" que significa "Japonês".',
        },
    },
    share: {
        title: "Compartilhar esta página",
    },
};
